import type { YoungSightWordEntry } from "@/types/youngLearner";

/**
 * The Dolch Primer, 1st Grade, and 2nd Grade sight-word lists — the
 * standard tiers that follow Pre-Primer (used in Kids Mode) in the
 * traditional Dolch progression. Same legitimacy tier as Pre-Primer: a
 * widely-taught, freely-reused word list, not any single publisher's
 * proprietary content. Sentences are written originally for this product.
 */
const RAW: Omit<YoungSightWordEntry, "id" | "slug">[] = [
  // --- Primer (52) ---
  { word: "all", tier: "primer", simpleSentence: "We ate all the popcorn." },
  { word: "am", tier: "primer", simpleSentence: "I am happy today." },
  { word: "are", tier: "primer", simpleSentence: "You are my friend." },
  { word: "at", tier: "primer", simpleSentence: "We are at the park." },
  { word: "ate", tier: "primer", simpleSentence: "She ate an apple." },
  { word: "be", tier: "primer", simpleSentence: "Please be quiet." },
  { word: "black", tier: "primer", simpleSentence: "The cat is black." },
  { word: "brown", tier: "primer", simpleSentence: "The bear is brown." },
  { word: "but", tier: "primer", simpleSentence: "I like cats, but not dogs." },
  { word: "came", tier: "primer", simpleSentence: "My friend came over." },
  { word: "did", tier: "primer", simpleSentence: "Did you finish your homework?" },
  { word: "do", tier: "primer", simpleSentence: "What do you want to eat?" },
  { word: "eat", tier: "primer", simpleSentence: "Let's eat dinner." },
  { word: "four", tier: "primer", simpleSentence: "I have four crayons." },
  { word: "get", tier: "primer", simpleSentence: "Can you get the ball?" },
  { word: "good", tier: "primer", simpleSentence: "That was a good movie." },
  { word: "have", tier: "primer", simpleSentence: "I have a new bike." },
  { word: "he", tier: "primer", simpleSentence: "He likes to swim." },
  { word: "into", tier: "primer", simpleSentence: "The cat jumped into the box." },
  { word: "like", tier: "primer", simpleSentence: "I like ice cream." },
  { word: "must", tier: "primer", simpleSentence: "We must go now." },
  { word: "new", tier: "primer", simpleSentence: "I got a new backpack." },
  { word: "no", tier: "primer", simpleSentence: "There is no more juice." },
  { word: "now", tier: "primer", simpleSentence: "Let's go outside now." },
  { word: "on", tier: "primer", simpleSentence: "The book is on the table." },
  { word: "our", tier: "primer", simpleSentence: "This is our classroom." },
  { word: "out", tier: "primer", simpleSentence: "The dog ran out the door." },
  { word: "please", tier: "primer", simpleSentence: "Please pass the salt." },
  { word: "pretty", tier: "primer", simpleSentence: "That is a pretty flower." },
  { word: "ran", tier: "primer", simpleSentence: "She ran to catch the bus." },
  { word: "ride", tier: "primer", simpleSentence: "I like to ride my bike." },
  { word: "saw", tier: "primer", simpleSentence: "We saw a rainbow." },
  { word: "say", tier: "primer", simpleSentence: "What did you say?" },
  { word: "she", tier: "primer", simpleSentence: "She plays the piano." },
  { word: "so", tier: "primer", simpleSentence: "I was so tired." },
  { word: "soon", tier: "primer", simpleSentence: "We will leave soon." },
  { word: "that", tier: "primer", simpleSentence: "I want that toy." },
  { word: "there", tier: "primer", simpleSentence: "Put it over there." },
  { word: "they", tier: "primer", simpleSentence: "They are my cousins." },
  { word: "this", tier: "primer", simpleSentence: "This is my favorite book." },
  { word: "too", tier: "primer", simpleSentence: "Can I come too?" },
  { word: "under", tier: "primer", simpleSentence: "The shoes are under the bed." },
  { word: "want", tier: "primer", simpleSentence: "I want to play outside." },
  { word: "was", tier: "primer", simpleSentence: "It was a sunny day." },
  { word: "well", tier: "primer", simpleSentence: "She sings very well." },
  { word: "went", tier: "primer", simpleSentence: "We went to the zoo." },
  { word: "what", tier: "primer", simpleSentence: "What time is it?" },
  { word: "white", tier: "primer", simpleSentence: "The snow is white." },
  { word: "who", tier: "primer", simpleSentence: "Who is at the door?" },
  { word: "will", tier: "primer", simpleSentence: "I will help you." },
  { word: "with", tier: "primer", simpleSentence: "I went with my sister." },
  { word: "yes", tier: "primer", simpleSentence: "Yes, I would love to." },

  // --- 1st Grade (41) ---
  { word: "after", tier: "grade1", simpleSentence: "We play after school." },
  { word: "again", tier: "grade1", simpleSentence: "Can you say that again?" },
  { word: "an", tier: "grade1", simpleSentence: "She ate an orange." },
  { word: "any", tier: "grade1", simpleSentence: "Do you have any pencils?" },
  { word: "as", tier: "grade1", simpleSentence: "He is as tall as me." },
  { word: "ask", tier: "grade1", simpleSentence: "You can ask a question." },
  { word: "by", tier: "grade1", simpleSentence: "We sat by the window." },
  { word: "could", tier: "grade1", simpleSentence: "Could you help me carry this?" },
  { word: "every", tier: "grade1", simpleSentence: "I brush my teeth every day." },
  { word: "fly", tier: "grade1", simpleSentence: "Birds can fly high." },
  { word: "from", tier: "grade1", simpleSentence: "This gift is from my aunt." },
  { word: "give", tier: "grade1", simpleSentence: "Can you give me the pen?" },
  { word: "going", tier: "grade1", simpleSentence: "We are going to the beach." },
  { word: "had", tier: "grade1", simpleSentence: "She had a great birthday." },
  { word: "has", tier: "grade1", simpleSentence: "He has a new puppy." },
  { word: "her", tier: "grade1", simpleSentence: "I gave the book to her." },
  { word: "him", tier: "grade1", simpleSentence: "I gave him the book." },
  { word: "his", tier: "grade1", simpleSentence: "This is his jacket." },
  { word: "how", tier: "grade1", simpleSentence: "How do you spell that?" },
  { word: "just", tier: "grade1", simpleSentence: "I just finished my homework." },
  { word: "know", tier: "grade1", simpleSentence: "Do you know the answer?" },
  { word: "let", tier: "grade1", simpleSentence: "Let me try that." },
  { word: "live", tier: "grade1", simpleSentence: "We live near the school." },
  { word: "may", tier: "grade1", simpleSentence: "May I go outside?" },
  { word: "of", tier: "grade1", simpleSentence: "This is a picture of my dog." },
  { word: "old", tier: "grade1", simpleSentence: "That is an old photograph." },
  { word: "once", tier: "grade1", simpleSentence: "We visited once before." },
  { word: "open", tier: "grade1", simpleSentence: "Please open the door." },
  { word: "over", tier: "grade1", simpleSentence: "The ball flew over the fence." },
  { word: "put", tier: "grade1", simpleSentence: "Put your shoes by the door." },
  { word: "round", tier: "grade1", simpleSentence: "The wheel is round." },
  { word: "some", tier: "grade1", simpleSentence: "Can I have some water?" },
  { word: "stop", tier: "grade1", simpleSentence: "Stop at the red light." },
  { word: "take", tier: "grade1", simpleSentence: "Take an umbrella with you." },
  { word: "thank", tier: "grade1", simpleSentence: "Thank you for the gift." },
  { word: "them", tier: "grade1", simpleSentence: "I saw them at the park." },
  { word: "then", tier: "grade1", simpleSentence: "First we eat, then we play." },
  { word: "think", tier: "grade1", simpleSentence: "I think it will rain." },
  { word: "walk", tier: "grade1", simpleSentence: "Let's walk to school today." },
  { word: "were", tier: "grade1", simpleSentence: "We were at the library." },
  { word: "when", tier: "grade1", simpleSentence: "When is your birthday?" },

  // --- 2nd Grade (46) ---
  { word: "always", tier: "grade2", simpleSentence: "She always says thank you." },
  { word: "around", tier: "grade2", simpleSentence: "We walked around the block." },
  { word: "because", tier: "grade2", simpleSentence: "I stayed home because I was sick." },
  { word: "been", tier: "grade2", simpleSentence: "I have been to that park before." },
  { word: "before", tier: "grade2", simpleSentence: "Wash your hands before dinner." },
  { word: "best", tier: "grade2", simpleSentence: "This is my best drawing yet." },
  { word: "both", tier: "grade2", simpleSentence: "Both of my parents like tea." },
  { word: "buy", tier: "grade2", simpleSentence: "We need to buy more milk." },
  { word: "call", tier: "grade2", simpleSentence: "I will call you tonight." },
  { word: "cold", tier: "grade2", simpleSentence: "It is cold outside today." },
  { word: "does", tier: "grade2", simpleSentence: "Does she like pizza?" },
  { word: "don't", tier: "grade2", simpleSentence: "I don't want to be late." },
  { word: "fast", tier: "grade2", simpleSentence: "The cheetah runs very fast." },
  { word: "first", tier: "grade2", simpleSentence: "She was first in line." },
  { word: "five", tier: "grade2", simpleSentence: "I have five fingers on each hand." },
  { word: "found", tier: "grade2", simpleSentence: "We found my lost shoe." },
  { word: "gave", tier: "grade2", simpleSentence: "He gave me a high five." },
  { word: "goes", tier: "grade2", simpleSentence: "This road goes to the beach." },
  { word: "green", tier: "grade2", simpleSentence: "The grass is green." },
  { word: "its", tier: "grade2", simpleSentence: "The dog wagged its tail." },
  { word: "made", tier: "grade2", simpleSentence: "I made a card for my mom." },
  { word: "many", tier: "grade2", simpleSentence: "There are many stars tonight." },
  { word: "off", tier: "grade2", simpleSentence: "Turn off the lights, please." },
  { word: "or", tier: "grade2", simpleSentence: "Do you want tea or juice?" },
  { word: "pull", tier: "grade2", simpleSentence: "Pull the door to open it." },
  { word: "read", tier: "grade2", simpleSentence: "I love to read books." },
  { word: "right", tier: "grade2", simpleSentence: "Turn right at the corner." },
  { word: "sing", tier: "grade2", simpleSentence: "We sing songs at school." },
  { word: "sit", tier: "grade2", simpleSentence: "Please sit down." },
  { word: "sleep", tier: "grade2", simpleSentence: "I sleep eight hours a night." },
  { word: "tell", tier: "grade2", simpleSentence: "Tell me a story." },
  { word: "their", tier: "grade2", simpleSentence: "That is their house." },
  { word: "these", tier: "grade2", simpleSentence: "These cookies are delicious." },
  { word: "those", tier: "grade2", simpleSentence: "Those shoes are new." },
  { word: "upon", tier: "grade2", simpleSentence: "Once upon a time..." },
  { word: "us", tier: "grade2", simpleSentence: "Come and join us." },
  { word: "use", tier: "grade2", simpleSentence: "You can use my pencil." },
  { word: "very", tier: "grade2", simpleSentence: "I am very excited." },
  { word: "wash", tier: "grade2", simpleSentence: "Please wash your hands." },
  { word: "which", tier: "grade2", simpleSentence: "Which color do you like best?" },
  { word: "why", tier: "grade2", simpleSentence: "Why is the sky blue?" },
  { word: "wish", tier: "grade2", simpleSentence: "I wish it would snow." },
  { word: "work", tier: "grade2", simpleSentence: "My dad goes to work early." },
  { word: "would", tier: "grade2", simpleSentence: "Would you like some cake?" },
  { word: "write", tier: "grade2", simpleSentence: "I like to write stories." },
  { word: "your", tier: "grade2", simpleSentence: "Is this your backpack?" },

  // --- 3rd Grade (41) ---
  { word: "about", tier: "grade3", simpleSentence: "Tell me about your weekend." },
  { word: "better", tier: "grade3", simpleSentence: "I feel better today." },
  { word: "bring", tier: "grade3", simpleSentence: "Please bring your homework." },
  { word: "carry", tier: "grade3", simpleSentence: "Can you carry this bag?" },
  { word: "clean", tier: "grade3", simpleSentence: "Please clean your room." },
  { word: "cut", tier: "grade3", simpleSentence: "I cut the paper with scissors." },
  { word: "done", tier: "grade3", simpleSentence: "I am done with my homework." },
  { word: "draw", tier: "grade3", simpleSentence: "I like to draw pictures." },
  { word: "drink", tier: "grade3", simpleSentence: "I drink water every day." },
  { word: "eight", tier: "grade3", simpleSentence: "I have eight crayons." },
  { word: "fall", tier: "grade3", simpleSentence: "Leaves fall in autumn." },
  { word: "far", tier: "grade3", simpleSentence: "The school is not far from here." },
  { word: "full", tier: "grade3", simpleSentence: "My cup is full of juice." },
  { word: "got", tier: "grade3", simpleSentence: "I got a new bike." },
  { word: "grow", tier: "grade3", simpleSentence: "Plants grow in the sun." },
  { word: "hold", tier: "grade3", simpleSentence: "Please hold my hand." },
  { word: "hot", tier: "grade3", simpleSentence: "The soup is very hot." },
  { word: "hurt", tier: "grade3", simpleSentence: "Did you hurt your knee?" },
  { word: "if", tier: "grade3", simpleSentence: "We can play outside if it's sunny." },
  { word: "keep", tier: "grade3", simpleSentence: "You can keep the toy." },
  { word: "kind", tier: "grade3", simpleSentence: "She is very kind to everyone." },
  { word: "laugh", tier: "grade3", simpleSentence: "The joke made us laugh." },
  { word: "light", tier: "grade3", simpleSentence: "Turn on the light, please." },
  { word: "long", tier: "grade3", simpleSentence: "The river is very long." },
  { word: "much", tier: "grade3", simpleSentence: "How much does it cost?" },
  { word: "myself", tier: "grade3", simpleSentence: "I can do it myself." },
  { word: "never", tier: "grade3", simpleSentence: "I never forget my lunch." },
  { word: "only", tier: "grade3", simpleSentence: "I only have one pencil left." },
  { word: "own", tier: "grade3", simpleSentence: "This is my own idea." },
  { word: "pick", tier: "grade3", simpleSentence: "Please pick a color." },
  { word: "seven", tier: "grade3", simpleSentence: "I have seven marbles." },
  { word: "shall", tier: "grade3", simpleSentence: "Shall we go now?" },
  { word: "show", tier: "grade3", simpleSentence: "Can you show me how?" },
  { word: "six", tier: "grade3", simpleSentence: "I have six stickers." },
  { word: "small", tier: "grade3", simpleSentence: "The kitten is very small." },
  { word: "start", tier: "grade3", simpleSentence: "Let's start the game." },
  { word: "ten", tier: "grade3", simpleSentence: "I can count to ten." },
  { word: "today", tier: "grade3", simpleSentence: "Today is a sunny day." },
  { word: "together", tier: "grade3", simpleSentence: "Let's build it together." },
  { word: "try", tier: "grade3", simpleSentence: "Please try your best." },
  { word: "warm", tier: "grade3", simpleSentence: "The blanket is warm and soft." },
];

function slugify(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export const YOUNG_SIGHT_WORDS: YoungSightWordEntry[] = RAW.map((entry) => {
  const slug = slugify(entry.word);
  return { ...entry, id: slug, slug };
});

export const YOUNG_SIGHT_WORDS_BY_SLUG: Record<string, YoungSightWordEntry> = Object.fromEntries(
  YOUNG_SIGHT_WORDS.map((w) => [w.slug, w])
);
