import type { IdiomEntry } from "@/types/idiom";

function slugify(idiom: string): string {
  return idiom.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/**
 * 155 common English idioms. All meanings, definitions, and examples are
 * written originally for this product. Idioms are everyday, widely-shared
 * language — not any single publisher's content — so coverage was chosen
 * for everyday usefulness, drawing on general knowledge of common English
 * idioms rather than any specific existing reference work.
 */
const RAW: Omit<IdiomEntry, "id" | "slug">[] = [
  // --- Body ---
  { idiom: "break a leg", category: "body", register: "informal",
    meaning: "Used to wish someone good luck, especially before a performance.",
    simpleDefinition: "Good luck!",
    examples: ["Break a leg tonight — you'll be great!", "Everyone told her to break a leg before the audition."] },
  { idiom: "cost an arm and a leg", category: "body", register: "informal",
    meaning: "To be very expensive.",
    simpleDefinition: "To be very expensive.",
    examples: ["That laptop cost an arm and a leg.", "Renting downtown costs an arm and a leg."] },
  { idiom: "get cold feet", category: "body", register: "informal",
    meaning: "To become nervous or hesitant about doing something you had planned to do.",
    simpleDefinition: "To suddenly feel too nervous to do something.",
    examples: ["He got cold feet before the wedding.", "Don't get cold feet now — you've prepared for this."] },
  { idiom: "keep an eye on", category: "body", register: "neutral",
    meaning: "To watch or monitor someone or something carefully.",
    simpleDefinition: "To watch carefully.",
    examples: ["Can you keep an eye on my bag?", "The doctor is keeping an eye on her recovery."] },
  { idiom: "pull someone's leg", category: "body", register: "informal",
    meaning: "To joke with someone or tease them, usually by telling them something untrue.",
    simpleDefinition: "To joke with someone.",
    examples: ["Relax, I'm just pulling your leg.", "He wasn't serious — he was pulling her leg."] },
  { idiom: "see eye to eye", category: "body", register: "neutral",
    meaning: "To agree with someone about something.",
    simpleDefinition: "To agree with someone.",
    examples: ["We don't always see eye to eye on politics.", "The siblings finally saw eye to eye."] },
  { idiom: "have a change of heart", category: "body", register: "neutral",
    meaning: "To change your opinion or feelings about something, often unexpectedly.",
    simpleDefinition: "To change your mind or feelings.",
    examples: ["She had a change of heart and decided to stay.", "He had a change of heart about selling the house."] },
  { idiom: "bite your tongue", category: "body", register: "informal",
    meaning: "To stop yourself from saying something, even though you want to.",
    simpleDefinition: "To hold back from saying something.",
    examples: ["I had to bite my tongue during the meeting.", "She bit her tongue instead of arguing."] },
  { idiom: "give someone the cold shoulder", category: "body", register: "informal",
    meaning: "To deliberately ignore someone or treat them in an unfriendly way.",
    simpleDefinition: "To ignore someone on purpose.",
    examples: ["She's been giving me the cold shoulder all week.", "He gave his coworker the cold shoulder after the argument."] },
  { idiom: "have your head in the clouds", category: "body", register: "informal",
    meaning: "To be daydreaming or unrealistic instead of paying attention to practical matters.",
    simpleDefinition: "To be daydreaming or unrealistic.",
    examples: ["Stop having your head in the clouds and focus.", "He's always got his head in the clouds."] },
  { idiom: "put your foot in your mouth", category: "body", register: "informal",
    meaning: "To say something embarrassing or tactless by accident.",
    simpleDefinition: "To accidentally say something embarrassing.",
    examples: ["I really put my foot in my mouth at dinner.", "She put her foot in her mouth asking about his divorce."] },
  { idiom: "twist someone's arm", category: "body", register: "informal",
    meaning: "To persuade someone to do something they were reluctant to do.",
    simpleDefinition: "To persuade someone strongly.",
    examples: ["Okay, you've twisted my arm — I'll come.", "It took some arm-twisting to get him to agree."] },
  { idiom: "keep your chin up", category: "body", register: "informal",
    meaning: "To stay positive and confident during a difficult time.",
    simpleDefinition: "To stay positive during a hard time.",
    examples: ["Keep your chin up — things will get better.", "She kept her chin up despite the setback."] },
  { idiom: "lend a hand", category: "body", register: "neutral",
    meaning: "To help someone with a task.",
    simpleDefinition: "To help someone.",
    examples: ["Could you lend a hand with these boxes?", "He always lends a hand when needed."] },
  { idiom: "rule of thumb", category: "body", register: "neutral",
    meaning: "A general, practical guideline based on experience rather than an exact rule.",
    simpleDefinition: "A general practical guideline.",
    examples: ["As a rule of thumb, arrive fifteen minutes early.", "A good rule of thumb is to save 20% of your income."] },

  // --- Animals ---
  { idiom: "let the cat out of the bag", category: "animals", register: "informal",
    meaning: "To reveal a secret, often by accident.",
    simpleDefinition: "To accidentally reveal a secret.",
    examples: ["She let the cat out of the bag about the surprise party.", "Don't let the cat out of the bag before we announce it."] },
  { idiom: "kill two birds with one stone", category: "animals", register: "neutral",
    meaning: "To achieve two things with a single action.",
    simpleDefinition: "To achieve two things at once.",
    examples: ["I killed two birds with one stone by exercising on my commute.", "Combining the trips killed two birds with one stone."] },
  { idiom: "the elephant in the room", category: "animals", register: "neutral",
    meaning: "An obvious problem or difficult subject that everyone notices but avoids discussing.",
    simpleDefinition: "An obvious problem no one wants to mention.",
    examples: ["Let's address the elephant in the room: the budget.", "Nobody mentioned the elephant in the room during dinner."] },
  { idiom: "once in a blue moon", category: "animals", register: "informal",
    meaning: "Very rarely.",
    simpleDefinition: "Very rarely.",
    examples: ["We only eat out once in a blue moon.", "He calls once in a blue moon."] },
  { idiom: "when pigs fly", category: "animals", register: "informal",
    meaning: "Used to say that something will never happen.",
    simpleDefinition: "Never (something impossible).",
    examples: ["He'll clean his room when pigs fly.", "\"Will she apologize?\" \"When pigs fly.\""] },
  { idiom: "hold your horses", category: "animals", register: "informal",
    meaning: "Used to tell someone to wait or slow down.",
    simpleDefinition: "Wait a moment; be patient.",
    examples: ["Hold your horses, we're not ready yet.", "Hold your horses — let's think this through."] },
  { idiom: "a wild goose chase", category: "animals", register: "informal",
    meaning: "A pointless search or pursuit that has no real chance of success.",
    simpleDefinition: "A pointless search.",
    examples: ["The whole errand turned into a wild goose chase.", "We went on a wild goose chase looking for the address."] },
  { idiom: "straight from the horse's mouth", category: "animals", register: "informal",
    meaning: "From a reliable, direct, or original source.",
    simpleDefinition: "From a reliable, direct source.",
    examples: ["I heard it straight from the horse's mouth.", "This is straight from the horse's mouth — the CEO told me himself."] },
  { idiom: "like a fish out of water", category: "animals", register: "informal",
    meaning: "Feeling uncomfortable or out of place in an unfamiliar situation.",
    simpleDefinition: "Feeling uncomfortable or out of place.",
    examples: ["He felt like a fish out of water at the formal dinner.", "She was a fish out of water in her new job at first."] },
  { idiom: "the early bird catches the worm", category: "animals", register: "neutral",
    meaning: "People who act early or arrive first have an advantage.",
    simpleDefinition: "Being early gives you an advantage.",
    examples: ["I always leave early — the early bird catches the worm.", "He got the best seat because the early bird catches the worm."] },
  { idiom: "let sleeping dogs lie", category: "animals", register: "neutral",
    meaning: "To avoid interfering with a situation that could cause problems if disturbed.",
    simpleDefinition: "To not disturb a settled situation.",
    examples: ["It's better to let sleeping dogs lie and not bring it up.", "I decided to let sleeping dogs lie about the old argument."] },
  { idiom: "a dog eat dog world", category: "animals", register: "informal",
    meaning: "A situation or environment that's fiercely competitive, where people act selfishly to succeed.",
    simpleDefinition: "A fiercely competitive environment.",
    examples: ["The tech industry can be a dog eat dog world.", "It's a dog eat dog world out there in sales."] },
  { idiom: "barking up the wrong tree", category: "animals", register: "informal",
    meaning: "To pursue a mistaken course of action, or to accuse the wrong person.",
    simpleDefinition: "To pursue a mistaken idea or blame the wrong person.",
    examples: ["If you think I did it, you're barking up the wrong tree.", "The investigators were barking up the wrong tree."] },
  { idiom: "smell a rat", category: "animals", register: "informal",
    meaning: "To suspect that something is wrong or dishonest.",
    simpleDefinition: "To suspect something is wrong.",
    examples: ["I smelled a rat when the numbers didn't match.", "She smelled a rat as soon as he avoided the question."] },
  { idiom: "birds of a feather flock together", category: "animals", register: "neutral",
    meaning: "People with similar interests or characters tend to spend time together.",
    simpleDefinition: "Similar people group together.",
    examples: ["They're best friends — birds of a feather flock together.", "It's no surprise they get along; birds of a feather flock together."] },

  // --- Food ---
  { idiom: "piece of cake", category: "food", register: "informal",
    meaning: "Something very easy to do.",
    simpleDefinition: "Something very easy.",
    examples: ["The exam was a piece of cake.", "Don't worry, this task is a piece of cake."] },
  { idiom: "spill the beans", category: "food", register: "informal",
    meaning: "To reveal secret information.",
    simpleDefinition: "To reveal a secret.",
    examples: ["Come on, spill the beans — what happened?", "He accidentally spilled the beans about the promotion."] },
  { idiom: "bring home the bacon", category: "food", register: "informal",
    meaning: "To earn money to support your family.",
    simpleDefinition: "To earn money for the family.",
    examples: ["She's the one bringing home the bacon these days.", "He works two jobs to bring home the bacon."] },
  { idiom: "have a lot on your plate", category: "food", register: "informal",
    meaning: "To have many things to deal with or a lot of responsibility.",
    simpleDefinition: "To be very busy with many things.",
    examples: ["I can't take on more right now — I have a lot on my plate.", "She's got a lot on her plate with the new baby and her job."] },
  { idiom: "the icing on the cake", category: "food", register: "informal",
    meaning: "An extra good thing added to a situation that was already good.",
    simpleDefinition: "An extra good thing on top of something good.",
    examples: ["Winning the award was the icing on the cake.", "The bonus was the icing on the cake after a great year."] },
  { idiom: "go bananas", category: "food", register: "informal",
    meaning: "To become extremely excited, angry, or crazy.",
    simpleDefinition: "To become very excited or crazy.",
    examples: ["The crowd went bananas when the team scored.", "He went bananas when he heard the news."] },
  { idiom: "in a nutshell", category: "food", register: "neutral",
    meaning: "Briefly, summarizing the main point.",
    simpleDefinition: "Briefly, in summary.",
    examples: ["In a nutshell, the project was a success.", "Let me explain it in a nutshell."] },
  { idiom: "that's the way the cookie crumbles", category: "food", register: "informal",
    meaning: "Used to accept a disappointing situation that can't be changed.",
    simpleDefinition: "That's just how things turned out.",
    examples: ["We didn't get the contract — that's the way the cookie crumbles.", "I was disappointed, but that's the way the cookie crumbles."] },
  { idiom: "sell like hot cakes", category: "food", register: "informal",
    meaning: "To sell very quickly and in large quantities.",
    simpleDefinition: "To sell very quickly.",
    examples: ["The new phone is selling like hot cakes.", "Tickets sold like hot cakes."] },
  { idiom: "cool as a cucumber", category: "food", register: "informal",
    meaning: "Very calm, especially in a stressful situation.",
    simpleDefinition: "Very calm under pressure.",
    examples: ["She stayed cool as a cucumber during the interview.", "He was cool as a cucumber despite the chaos."] },
  { idiom: "not my cup of tea", category: "food", register: "informal",
    meaning: "Not something you like or enjoy.",
    simpleDefinition: "Not something I like.",
    examples: ["Horror movies aren't really my cup of tea.", "Jazz just isn't his cup of tea."] },
  { idiom: "butter someone up", category: "food", register: "informal",
    meaning: "To flatter someone in order to gain a favor from them.",
    simpleDefinition: "To flatter someone to get something.",
    examples: ["He's buttering up the boss before asking for a raise.", "Stop trying to butter me up."] },

  // --- Weather ---
  { idiom: "under the weather", category: "weather", register: "informal",
    meaning: "Feeling slightly ill.",
    simpleDefinition: "Feeling a bit sick.",
    examples: ["I'm feeling a bit under the weather today.", "She stayed home because she was under the weather."] },
  { idiom: "steal someone's thunder", category: "weather", register: "informal",
    meaning: "To take credit or attention that should belong to someone else.",
    simpleDefinition: "To take credit that belongs to someone else.",
    examples: ["He stole my thunder by announcing the news first.", "Don't steal her thunder — let her share the good news."] },
  { idiom: "on cloud nine", category: "weather", register: "informal",
    meaning: "Extremely happy.",
    simpleDefinition: "Extremely happy.",
    examples: ["She's been on cloud nine since the engagement.", "He was on cloud nine after the promotion."] },
  { idiom: "a storm in a teacup", category: "weather", register: "informal",
    meaning: "A lot of fuss or anger about something unimportant.",
    simpleDefinition: "A lot of fuss over something small.",
    examples: ["The disagreement was just a storm in a teacup.", "It'll blow over — it's a storm in a teacup."] },
  { idiom: "come rain or shine", category: "weather", register: "neutral",
    meaning: "Regardless of circumstances or difficulties.",
    simpleDefinition: "No matter what happens.",
    examples: ["We'll be there, come rain or shine.", "He goes running every morning, come rain or shine."] },
  { idiom: "chase rainbows", category: "weather", register: "informal",
    meaning: "To pursue goals that are unrealistic or impossible to achieve.",
    simpleDefinition: "To chase unrealistic goals.",
    examples: ["He's been chasing rainbows with that business idea.", "Stop chasing rainbows and focus on something achievable."] },
  { idiom: "it never rains but it pours", category: "weather", register: "informal",
    meaning: "Used when several bad things happen at the same time.",
    simpleDefinition: "Bad things tend to happen all at once.",
    examples: ["First I lost my job, then my car broke down — it never rains but it pours.", "It never rains but it pours; nothing's gone right this week."] },
  { idiom: "weather the storm", category: "weather", register: "neutral",
    meaning: "To survive a difficult period or crisis.",
    simpleDefinition: "To survive a difficult period.",
    examples: ["The company managed to weather the storm during the recession.", "They weathered the storm together as a family."] },

  // --- Colors ---
  { idiom: "out of the blue", category: "colors", register: "informal",
    meaning: "Unexpectedly, without warning.",
    simpleDefinition: "Suddenly, without warning.",
    examples: ["He called me out of the blue after years of silence.", "The offer came completely out of the blue."] },
  { idiom: "green with envy", category: "colors", register: "informal",
    meaning: "Extremely jealous.",
    simpleDefinition: "Very jealous.",
    examples: ["She was green with envy over her friend's new car.", "He turned green with envy when he saw the vacation photos."] },
  { idiom: "caught red-handed", category: "colors", register: "informal",
    meaning: "Caught in the act of doing something wrong.",
    simpleDefinition: "Caught doing something wrong.",
    examples: ["The thief was caught red-handed.", "He was caught red-handed eating the last slice of cake."] },
  { idiom: "see red", category: "colors", register: "informal",
    meaning: "To become very angry suddenly.",
    simpleDefinition: "To become very angry.",
    examples: ["I saw red when he lied to my face.", "She saw red after reading the unfair review."] },
  { idiom: "a white lie", category: "colors", register: "neutral",
    meaning: "A small, harmless lie, often told to avoid hurting someone's feelings.",
    simpleDefinition: "A small, harmless lie.",
    examples: ["I told a white lie about liking the gift.", "Sometimes a white lie is kinder than the truth."] },
  { idiom: "give someone the green light", category: "colors", register: "informal",
    meaning: "To give permission for something to proceed.",
    simpleDefinition: "To give permission to proceed.",
    examples: ["The manager gave us the green light to start the project.", "We're waiting for the green light from legal."] },
  { idiom: "in the black", category: "colors", register: "neutral",
    meaning: "Financially profitable; not in debt.",
    simpleDefinition: "Making a profit; not in debt.",
    examples: ["The company is finally back in the black.", "We stayed in the black despite the slow year."] },
  { idiom: "in the red", category: "colors", register: "neutral",
    meaning: "In debt; losing money.",
    simpleDefinition: "In debt; losing money.",
    examples: ["The business has been in the red for months.", "We went into the red after the renovation."] },

  // --- Money ---
  { idiom: "break the bank", category: "money", register: "informal",
    meaning: "To cost too much money, or use up all your money.",
    simpleDefinition: "To cost too much money.",
    examples: ["A nice dinner out won't break the bank.", "We don't need to break the bank for a good vacation."] },
  { idiom: "cost a fortune", category: "money", register: "informal",
    meaning: "To be very expensive.",
    simpleDefinition: "To be very expensive.",
    examples: ["That ring must have cost a fortune.", "Fixing the roof cost a fortune."] },
  { idiom: "born with a silver spoon in your mouth", category: "money", register: "informal",
    meaning: "Born into a wealthy family.",
    simpleDefinition: "Born into wealth.",
    examples: ["He was born with a silver spoon in his mouth.", "She never had to struggle — born with a silver spoon in her mouth."] },
  { idiom: "tighten your belt", category: "money", register: "informal",
    meaning: "To spend less money than before, usually because of financial difficulty.",
    simpleDefinition: "To spend less money.",
    examples: ["We had to tighten our belts after I lost my job.", "The company is tightening its belt this quarter."] },
  { idiom: "money doesn't grow on trees", category: "money", register: "informal",
    meaning: "Used to remind someone that money is limited and should be spent carefully.",
    simpleDefinition: "Money is limited; don't waste it.",
    examples: ["I told the kids money doesn't grow on trees.", "You can't buy everything — money doesn't grow on trees."] },
  { idiom: "pinch pennies", category: "money", register: "informal",
    meaning: "To be very careful and frugal with spending.",
    simpleDefinition: "To spend very carefully.",
    examples: ["We've been pinching pennies to save for the trip.", "She pinches pennies wherever she can."] },
  { idiom: "go dutch", category: "money", register: "informal",
    meaning: "To split the cost of something, especially a meal, equally between everyone.",
    simpleDefinition: "To each pay your own share.",
    examples: ["Let's go dutch on dinner tonight.", "They always go dutch when they eat out."] },
  { idiom: "nest egg", category: "money", register: "neutral",
    meaning: "Money saved for the future.",
    simpleDefinition: "Savings for the future.",
    examples: ["They've built up a nice nest egg for retirement.", "This bonus will add to my nest egg."] },
  { idiom: "on a shoestring", category: "money", register: "informal",
    meaning: "With very little money.",
    simpleDefinition: "With very little money.",
    examples: ["We traveled around Europe on a shoestring.", "The film was made on a shoestring budget."] },

  // --- Time ---
  { idiom: "around the clock", category: "time", register: "neutral",
    meaning: "Continuously, all day and night.",
    simpleDefinition: "Continuously, all the time.",
    examples: ["The factory operates around the clock.", "Doctors worked around the clock during the crisis."] },
  { idiom: "in the nick of time", category: "time", register: "informal",
    meaning: "Just in time; at the last possible moment.",
    simpleDefinition: "Just in time, at the last moment.",
    examples: ["We caught the train in the nick of time.", "The ambulance arrived in the nick of time."] },
  { idiom: "time flies", category: "time", register: "informal",
    meaning: "Time passes very quickly.",
    simpleDefinition: "Time passes quickly.",
    examples: ["Time flies when you're having fun.", "I can't believe it's already December — time flies."] },
  { idiom: "a blessing in disguise", category: "time", register: "neutral",
    meaning: "Something that seems bad or unlucky at first but turns out to have a good result.",
    simpleDefinition: "Something bad that turns out to be good.",
    examples: ["Losing that job was a blessing in disguise.", "The delay turned out to be a blessing in disguise."] },
  { idiom: "better late than never", category: "time", register: "neutral",
    meaning: "It's better to do or arrive at something late than not at all.",
    simpleDefinition: "Doing it late is better than not doing it.",
    examples: ["He finally apologized — better late than never.", "She joined the meeting an hour late, but better late than never."] },
  { idiom: "in the long run", category: "time", register: "neutral",
    meaning: "Over an extended period of time; eventually.",
    simpleDefinition: "Over a long period of time.",
    examples: ["It'll pay off in the long run.", "Saving now helps in the long run."] },
  { idiom: "against the clock", category: "time", register: "neutral",
    meaning: "Racing to finish something before a deadline.",
    simpleDefinition: "Racing to meet a deadline.",
    examples: ["We were working against the clock to finish the report.", "It's a race against the clock to fix the issue."] },

  // --- Emotions & state ---
  { idiom: "over the moon", category: "emotions", register: "informal",
    meaning: "Extremely happy or delighted.",
    simpleDefinition: "Extremely happy.",
    examples: ["She was over the moon about the acceptance letter.", "We're over the moon with the results."] },
  { idiom: "down in the dumps", category: "emotions", register: "informal",
    meaning: "Feeling sad or depressed.",
    simpleDefinition: "Feeling sad.",
    examples: ["He's been down in the dumps since the breakup.", "Why are you so down in the dumps today?"] },
  { idiom: "butterflies in your stomach", category: "emotions", register: "informal",
    meaning: "A nervous, fluttery feeling before something important.",
    simpleDefinition: "Nervous excitement before something important.",
    examples: ["I had butterflies in my stomach before the interview.", "She gets butterflies whenever she performs."] },
  { idiom: "at the end of your rope", category: "emotions", register: "informal",
    meaning: "Having no patience or energy left; at the limit of what you can tolerate.",
    simpleDefinition: "Out of patience or energy.",
    examples: ["After the long week, I was at the end of my rope.", "She's at the end of her rope with the noisy neighbors."] },
  { idiom: "a heart of gold", category: "emotions", register: "neutral",
    meaning: "A very kind and generous nature.",
    simpleDefinition: "Very kind and generous.",
    examples: ["She has a heart of gold — always helping others.", "Despite his tough exterior, he has a heart of gold."] },
  { idiom: "keep your cool", category: "emotions", register: "informal",
    meaning: "To stay calm, especially in a stressful or provoking situation.",
    simpleDefinition: "To stay calm.",
    examples: ["Try to keep your cool during the negotiation.", "She kept her cool even when things went wrong."] },
  { idiom: "lose your temper", category: "emotions", register: "neutral",
    meaning: "To suddenly become very angry.",
    simpleDefinition: "To suddenly become very angry.",
    examples: ["He lost his temper during the meeting.", "Try not to lose your temper with the kids."] },
  { idiom: "on edge", category: "emotions", register: "informal",
    meaning: "Nervous, tense, or anxious.",
    simpleDefinition: "Nervous or anxious.",
    examples: ["I've been on edge all day waiting for the results.", "The whole team was on edge before the presentation."] },
  { idiom: "in high spirits", category: "emotions", register: "neutral",
    meaning: "Feeling happy, cheerful, and enthusiastic.",
    simpleDefinition: "Feeling happy and enthusiastic.",
    examples: ["Everyone was in high spirits at the party.", "The team was in high spirits after the win."] },
  { idiom: "burst into tears", category: "emotions", register: "neutral",
    meaning: "To suddenly start crying.",
    simpleDefinition: "To suddenly start crying.",
    examples: ["She burst into tears when she heard the news.", "He burst into tears of joy at the wedding."] },
  { idiom: "take it with a grain of salt", category: "emotions", register: "informal",
    meaning: "To not fully believe something; to be skeptical of it.",
    simpleDefinition: "To be a bit skeptical of something.",
    examples: ["Take his advice with a grain of salt.", "I'd take that rumor with a grain of salt."] },
  { idiom: "bite the bullet", category: "emotions", register: "informal",
    meaning: "To force yourself to do something unpleasant or difficult that you've been avoiding.",
    simpleDefinition: "To force yourself to do something unpleasant.",
    examples: ["I finally bit the bullet and went to the dentist.", "We bit the bullet and fixed the car."] },

  // --- Work & business ---
  { idiom: "get the ball rolling", category: "work-business", register: "informal",
    meaning: "To start a process or activity.",
    simpleDefinition: "To start something.",
    examples: ["Let's get the ball rolling on the new project.", "She got the ball rolling with a quick introduction."] },
  { idiom: "back to the drawing board", category: "work-business", register: "informal",
    meaning: "To start over after a plan or attempt has failed.",
    simpleDefinition: "To start over after failure.",
    examples: ["The design didn't work, so it's back to the drawing board.", "That pitch failed — back to the drawing board."] },
  { idiom: "learn the ropes", category: "work-business", register: "informal",
    meaning: "To learn how to do a new job or task.",
    simpleDefinition: "To learn how to do a new job.",
    examples: ["It took a few weeks to learn the ropes.", "She's still learning the ropes at her new job."] },
  { idiom: "think outside the box", category: "work-business", register: "neutral",
    meaning: "To think creatively, beyond conventional or expected ideas.",
    simpleDefinition: "To think creatively.",
    examples: ["We need to think outside the box for this campaign.", "He's known for thinking outside the box."] },
  { idiom: "go the extra mile", category: "work-business", register: "neutral",
    meaning: "To make more effort than is expected or required.",
    simpleDefinition: "To make extra effort.",
    examples: ["She always goes the extra mile for her clients.", "The staff went the extra mile to help us."] },
  { idiom: "burn the midnight oil", category: "work-business", register: "informal",
    meaning: "To work late into the night.",
    simpleDefinition: "To work late into the night.",
    examples: ["I've been burning the midnight oil to finish the report.", "She burned the midnight oil studying for finals."] },
  { idiom: "climb the corporate ladder", category: "work-business", register: "neutral",
    meaning: "To advance to higher positions within a company or career.",
    simpleDefinition: "To advance in your career.",
    examples: ["He's been steadily climbing the corporate ladder.", "She climbed the corporate ladder in just five years."] },
  { idiom: "touch base", category: "work-business", register: "informal",
    meaning: "To make brief contact with someone, often to give or get an update.",
    simpleDefinition: "To make brief contact for an update.",
    examples: ["Let's touch base next week about the project.", "I wanted to touch base before the deadline."] },
  { idiom: "on the same page", category: "work-business", register: "informal",
    meaning: "In agreement, or having the same understanding about something.",
    simpleDefinition: "In agreement or understanding.",
    examples: ["Let's make sure we're on the same page before the meeting.", "The team is finally on the same page."] },
  { idiom: "put all your eggs in one basket", category: "work-business", register: "neutral",
    meaning: "To risk everything on the success of one plan or venture.",
    simpleDefinition: "To risk everything on one plan.",
    examples: ["It's risky to put all your eggs in one basket with a single client.", "Diversify — don't put all your eggs in one basket."] },
  { idiom: "call it a day", category: "work-business", register: "informal",
    meaning: "To stop working on something for the day.",
    simpleDefinition: "To stop working for the day.",
    examples: ["Let's call it a day and finish tomorrow.", "We called it a day after eight hours of painting."] },

  // --- Communication ---
  { idiom: "beat around the bush", category: "communication", register: "informal",
    meaning: "To avoid talking about something directly.",
    simpleDefinition: "To avoid getting to the point.",
    examples: ["Stop beating around the bush and tell me what happened.", "She beat around the bush instead of answering."] },
  { idiom: "get to the point", category: "communication", register: "neutral",
    meaning: "To say the main thing directly, without unnecessary detail.",
    simpleDefinition: "To say the main thing directly.",
    examples: ["Can you get to the point? We're short on time.", "He finally got to the point after a long story."] },
  { idiom: "hit the nail on the head", category: "communication", register: "informal",
    meaning: "To describe or identify something exactly right.",
    simpleDefinition: "To describe something exactly right.",
    examples: ["You hit the nail on the head with that comment.", "Her analysis really hit the nail on the head."] },
  { idiom: "read between the lines", category: "communication", register: "neutral",
    meaning: "To understand a hidden or implied meaning, not just the literal words.",
    simpleDefinition: "To understand the hidden meaning.",
    examples: ["Reading between the lines, I think he's not happy here.", "You have to read between the lines with her emails."] },
  { idiom: "speak of the devil", category: "communication", register: "informal",
    meaning: "Said when someone who was just being talked about suddenly appears.",
    simpleDefinition: "Said when someone appears right after being mentioned.",
    examples: ["Speak of the devil — here she comes now!", "We were just talking about you — speak of the devil."] },
  { idiom: "a picture is worth a thousand words", category: "communication", register: "neutral",
    meaning: "An image can convey a complex idea more effectively than a description.",
    simpleDefinition: "Images can say more than words.",
    examples: ["Just look at the chart — a picture is worth a thousand words.", "The photo said it all; a picture is worth a thousand words."] },
  { idiom: "put words in someone's mouth", category: "communication", register: "neutral",
    meaning: "To claim someone said something they didn't actually say, or misrepresent their words.",
    simpleDefinition: "To misrepresent what someone said.",
    examples: ["Don't put words in my mouth — that's not what I meant.", "He accused her of putting words in his mouth."] },
  { idiom: "keep someone posted", category: "communication", register: "informal",
    meaning: "To keep someone informed about developments.",
    simpleDefinition: "To keep someone informed.",
    examples: ["I'll keep you posted on the results.", "Please keep us posted about any changes."] },
  { idiom: "long story short", category: "communication", register: "informal",
    meaning: "Used to summarize something briefly, skipping the details.",
    simpleDefinition: "To summarize briefly.",
    examples: ["Long story short, we missed the flight.", "Long story short, the deal fell through."] },
  { idiom: "word of mouth", category: "communication", register: "neutral",
    meaning: "Information spread informally from person to person, rather than through advertising.",
    simpleDefinition: "Information spread person to person.",
    examples: ["The restaurant became popular through word of mouth.", "We found our plumber by word of mouth."] },

  // --- Success & failure ---
  { idiom: "hit the jackpot", category: "success-failure", register: "informal",
    meaning: "To have great success or good fortune, often unexpectedly.",
    simpleDefinition: "To have great, often unexpected success.",
    examples: ["We hit the jackpot with this apartment.", "The startup hit the jackpot with its first product."] },
  { idiom: "go back to square one", category: "success-failure", register: "informal",
    meaning: "To start over from the beginning after a failed attempt.",
    simpleDefinition: "To start over from the beginning.",
    examples: ["The deal fell through, so we're back to square one.", "After the rejection, it was back to square one."] },
  { idiom: "miss the boat", category: "success-failure", register: "informal",
    meaning: "To miss an opportunity by being too slow to act.",
    simpleDefinition: "To miss an opportunity.",
    examples: ["He missed the boat on the early investment.", "Don't miss the boat — apply before the deadline."] },
  { idiom: "make or break", category: "success-failure", register: "neutral",
    meaning: "Something that will determine whether a situation succeeds or fails completely.",
    simpleDefinition: "Something that decides success or failure.",
    examples: ["This presentation could make or break the deal.", "It's a make or break moment for the team."] },
  { idiom: "the ball is in your court", category: "success-failure", register: "informal",
    meaning: "It's your turn to take action or make a decision.",
    simpleDefinition: "It's your turn to act.",
    examples: ["I've done my part — the ball is in your court now.", "The ball's in their court to respond."] },
  { idiom: "against all odds", category: "success-failure", register: "neutral",
    meaning: "Despite very difficult circumstances; when success seemed unlikely.",
    simpleDefinition: "Despite great difficulty.",
    examples: ["Against all odds, they won the championship.", "She succeeded against all odds."] },
  { idiom: "fall through", category: "success-failure", register: "informal",
    meaning: "For a plan to fail to happen.",
    simpleDefinition: "For a plan to fail.",
    examples: ["Our vacation plans fell through.", "The merger fell through at the last minute."] },
  { idiom: "come out on top", category: "success-failure", register: "informal",
    meaning: "To succeed or win, especially after a difficult competition or struggle.",
    simpleDefinition: "To succeed or win in the end.",
    examples: ["Despite the setbacks, she came out on top.", "Our team came out on top in the finals."] },
  { idiom: "throw in the towel", category: "success-failure", register: "informal",
    meaning: "To give up; to admit defeat.",
    simpleDefinition: "To give up.",
    examples: ["After three failed attempts, he threw in the towel.", "Don't throw in the towel yet — keep trying."] },

  // --- Difficulty ---
  { idiom: "between a rock and a hard place", category: "difficulty", register: "informal",
    meaning: "Facing a difficult choice between two equally unpleasant options.",
    simpleDefinition: "Facing a difficult choice.",
    examples: ["I'm between a rock and a hard place with this decision.", "She was between a rock and a hard place — quit or stay unhappy."] },
  { idiom: "an uphill battle", category: "difficulty", register: "neutral",
    meaning: "A difficult struggle that requires great effort.",
    simpleDefinition: "A difficult struggle.",
    examples: ["Getting funding was an uphill battle.", "It's been an uphill battle recovering from the injury."] },
  { idiom: "bite off more than you can chew", category: "difficulty", register: "informal",
    meaning: "To take on more responsibility or work than you can handle.",
    simpleDefinition: "To take on too much.",
    examples: ["I think I bit off more than I could chew with this project.", "He bit off more than he could chew running two businesses."] },
  { idiom: "caught in the crossfire", category: "difficulty", register: "neutral",
    meaning: "Caught in the middle of a conflict between other people.",
    simpleDefinition: "Caught in the middle of others' conflict.",
    examples: ["The interns got caught in the crossfire of the managers' dispute.", "She felt caught in the crossfire between her parents."] },
  { idiom: "go through the mill", category: "difficulty", register: "informal",
    meaning: "To have a very difficult or exhausting experience.",
    simpleDefinition: "To have a very hard experience.",
    examples: ["He's really gone through the mill this year.", "The team went through the mill during the audit."] },
  { idiom: "jump through hoops", category: "difficulty", register: "informal",
    meaning: "To go through many difficult or complicated steps to achieve something.",
    simpleDefinition: "To go through many difficult steps.",
    examples: ["We had to jump through hoops to get the visa.", "She jumped through hoops to get the refund."] },
  { idiom: "a tough nut to crack", category: "difficulty", register: "informal",
    meaning: "A difficult problem to solve, or a person who is hard to understand or persuade.",
    simpleDefinition: "A difficult problem or person.",
    examples: ["This puzzle is a tough nut to crack.", "The client was a tough nut to crack."] },
  { idiom: "easier said than done", category: "difficulty", register: "neutral",
    meaning: "Used to say that something is harder to do than to talk about.",
    simpleDefinition: "It's harder to do than to say.",
    examples: ["Losing weight is easier said than done.", "\"Just relax,\" she said — easier said than done."] },
  { idiom: "at your wit's end", category: "difficulty", register: "informal",
    meaning: "Extremely frustrated and out of ideas for solving a problem.",
    simpleDefinition: "Extremely frustrated, out of solutions.",
    examples: ["I'm at my wit's end with this printer.", "She was at her wit's end trying to calm the baby."] },

  // --- General ---
  { idiom: "actions speak louder than words", category: "general", register: "neutral",
    meaning: "What people do matters more than what they say.",
    simpleDefinition: "What you do matters more than what you say.",
    examples: ["He apologized, but actions speak louder than words.", "Show me, don't just tell me — actions speak louder than words."] },
  { idiom: "the best of both worlds", category: "general", register: "neutral",
    meaning: "A situation that combines the advantages of two different things.",
    simpleDefinition: "The advantages of two things combined.",
    examples: ["Working remotely gives her the best of both worlds.", "The hybrid car offers the best of both worlds."] },
  { idiom: "break the ice", category: "general", register: "informal",
    meaning: "To do or say something to relieve tension or start a conversation in a social situation.",
    simpleDefinition: "To relieve tension and start talking.",
    examples: ["He told a joke to break the ice.", "The game was a great way to break the ice at the party."] },
  { idiom: "by the skin of your teeth", category: "general", register: "informal",
    meaning: "To barely succeed at something; only just manage to do it.",
    simpleDefinition: "To barely succeed.",
    examples: ["We caught the flight by the skin of our teeth.", "She passed the exam by the skin of her teeth."] },
  { idiom: "curiosity killed the cat", category: "general", register: "informal",
    meaning: "Used to warn someone that being too curious can get them into trouble.",
    simpleDefinition: "Being too curious can cause trouble.",
    examples: ["Don't pry too much — curiosity killed the cat.", "He learned the hard way that curiosity killed the cat."] },
  { idiom: "don't judge a book by its cover", category: "general", register: "neutral",
    meaning: "Don't form an opinion about someone or something based only on appearance.",
    simpleDefinition: "Don't judge by appearance alone.",
    examples: ["He seemed unfriendly, but don't judge a book by its cover.", "The shop looks small, but don't judge a book by its cover."] },
  { idiom: "every cloud has a silver lining", category: "general", register: "neutral",
    meaning: "Even difficult or unfortunate situations have some positive aspect.",
    simpleDefinition: "Bad situations have some good aspect.",
    examples: ["We lost the game, but every cloud has a silver lining — we learned a lot.", "Every cloud has a silver lining; the delay gave us more time to prepare."] },
  { idiom: "go with the flow", category: "general", register: "informal",
    meaning: "To relax and accept things as they happen, without resisting.",
    simpleDefinition: "To accept things as they happen.",
    examples: ["I don't have a plan — let's just go with the flow.", "She's easygoing and likes to go with the flow."] },
  { idiom: "hit the road", category: "general", register: "informal",
    meaning: "To leave or begin a journey.",
    simpleDefinition: "To leave or start a trip.",
    examples: ["We should hit the road before traffic gets bad.", "Time to hit the road — see you next week!"] },
  { idiom: "it's not rocket science", category: "general", register: "informal",
    meaning: "Used to say that something isn't difficult to understand or do.",
    simpleDefinition: "It's not difficult.",
    examples: ["Come on, it's not rocket science.", "Setting up the printer isn't rocket science."] },
  { idiom: "let bygones be bygones", category: "general", register: "neutral",
    meaning: "To forgive and forget a past conflict or disagreement.",
    simpleDefinition: "To forgive and forget the past.",
    examples: ["It's time to let bygones be bygones.", "They decided to let bygones be bygones after years apart."] },
  { idiom: "out of the woods", category: "general", register: "informal",
    meaning: "Past the most difficult or dangerous part of a situation.",
    simpleDefinition: "Past the most difficult part.",
    examples: ["The patient is stable, but not out of the woods yet.", "We're finally out of the woods with the project."] },
  { idiom: "the tip of the iceberg", category: "general", register: "neutral",
    meaning: "A small, visible part of a much larger problem or situation.",
    simpleDefinition: "A small visible part of a bigger problem.",
    examples: ["These complaints are just the tip of the iceberg.", "The delay was only the tip of the iceberg."] },
  { idiom: "when in rome, do as the romans do", category: "general", register: "neutral",
    meaning: "You should follow the customs of the place or situation you're in.",
    simpleDefinition: "Follow local customs when somewhere new.",
    examples: ["I tried the local dish — when in Rome, do as the Romans do.", "She adopted the local dress code: when in Rome."] },
  { idiom: "add insult to injury", category: "general", register: "neutral",
    meaning: "To make a bad situation even worse.",
    simpleDefinition: "To make a bad situation worse.",
    examples: ["To add insult to injury, it started raining after we lost.", "The fee for the delay added insult to injury."] },
  { idiom: "beat a dead horse", category: "general", register: "informal",
    meaning: "To continue focusing on a subject that's already been settled or is pointless to pursue further.",
    simpleDefinition: "To keep discussing something already settled.",
    examples: ["We've decided — let's not beat a dead horse.", "He kept beating a dead horse about the old plan."] },
  { idiom: "cut corners", category: "general", register: "informal",
    meaning: "To do something in the easiest or cheapest way, often sacrificing quality.",
    simpleDefinition: "To do something cheaply/carelessly.",
    examples: ["They cut corners on the construction, and it showed.", "Don't cut corners when it comes to safety."] },
  { idiom: "draw the line", category: "general", register: "neutral",
    meaning: "To set a limit on what you will accept or do.",
    simpleDefinition: "To set a limit.",
    examples: ["I draw the line at working weekends.", "We have to draw the line somewhere."] },
  { idiom: "face the music", category: "general", register: "informal",
    meaning: "To accept the consequences of your actions, especially unpleasant ones.",
    simpleDefinition: "To accept the consequences.",
    examples: ["It's time to face the music and admit the mistake.", "He finally faced the music after avoiding it for weeks."] },
  { idiom: "get out of hand", category: "general", register: "informal",
    meaning: "To become uncontrollable.",
    simpleDefinition: "To become uncontrollable.",
    examples: ["The party got out of hand pretty quickly.", "Costs got out of hand during the renovation."] },
  { idiom: "in over your head", category: "general", register: "informal",
    meaning: "In a situation that's too difficult for you to handle.",
    simpleDefinition: "In a situation too difficult to handle.",
    examples: ["I think he's in over his head with this project.", "She felt in over her head at the new job."] },
  { idiom: "keep it under your hat", category: "general", register: "informal",
    meaning: "To keep something secret; not tell anyone.",
    simpleDefinition: "To keep something secret.",
    examples: ["Keep it under your hat, but we're expecting a baby.", "Please keep this news under your hat for now."] },
  { idiom: "on the fence", category: "general", register: "informal",
    meaning: "Undecided about something.",
    simpleDefinition: "Undecided about something.",
    examples: ["I'm still on the fence about the job offer.", "She's on the fence about moving abroad."] },
  { idiom: "play devil's advocate", category: "general", register: "neutral",
    meaning: "To argue the opposite side of a debate, not necessarily because you believe it, but to encourage discussion.",
    simpleDefinition: "To argue the opposite side for debate.",
    examples: ["Let me play devil's advocate for a moment.", "He likes to play devil's advocate in meetings."] },
  { idiom: "take the bull by the horns", category: "general", register: "informal",
    meaning: "To confront a difficult situation directly and with confidence.",
    simpleDefinition: "To confront a difficulty directly.",
    examples: ["She took the bull by the horns and fixed the issue herself.", "It's time to take the bull by the horns."] },
  { idiom: "the last straw", category: "general", register: "informal",
    meaning: "The final problem in a series that makes someone lose patience completely.",
    simpleDefinition: "The final problem that ends your patience.",
    examples: ["The third delay was the last straw.", "His comment was the last straw for her."] },
  { idiom: "up in the air", category: "general", register: "informal",
    meaning: "Undecided or uncertain.",
    simpleDefinition: "Undecided or uncertain.",
    examples: ["Our travel plans are still up in the air.", "Whether we'll get funding is up in the air."] },
  { idiom: "wrap your head around", category: "general", register: "informal",
    meaning: "To understand something complicated or hard to accept.",
    simpleDefinition: "To understand something complex.",
    examples: ["I can't wrap my head around the new policy.", "It took a while to wrap my head around the results."] },
  { idiom: "a piece of the pie", category: "general", register: "informal",
    meaning: "A share of something, especially profits or benefits.",
    simpleDefinition: "A share of something, especially profits.",
    examples: ["Everyone wants a piece of the pie in this market.", "The investors each got a piece of the pie."] },
];

export const IDIOMS: IdiomEntry[] = RAW.map((entry) => {
  const slug = slugify(entry.idiom);
  return { ...entry, id: slug, slug };
});

export const IDIOMS_BY_SLUG: Record<string, IdiomEntry> = Object.fromEntries(
  IDIOMS.map((i) => [i.slug, i])
);
