import type { DiscoveryEntry } from "@/types/discovery";

function slugify(name: string): string {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/**
 * 90 entries (15 per category) for the Discovery encyclopedia section. All
 * facts are original, general knowledge — written fresh for this product,
 * not sourced from or checked against any specific encyclopedia.
 */
const RAW: Omit<DiscoveryEntry, "id" | "slug">[] = [
  // ============ ANIMALS & NATURE ============
  { name: "Lion", category: "animals", emoji: "🦁",
    simpleFact: "The lion is called the king of the jungle, even though it really lives on grassy plains.",
    facts: ["Lions live in groups called prides, usually led by related females.", "A male lion's roar can be heard up to 5 miles (8 km) away.", "Lions mostly hunt at night and sleep up to 20 hours a day."],
    funFact: "A lion's roar is loud enough to be heard almost five miles away!" },
  { name: "Elephant", category: "animals", emoji: "🐘",
    simpleFact: "Elephants are the biggest land animals on Earth.",
    facts: ["An elephant's trunk has no bones and can grip like a hand.", "Elephants can remember other elephants and places for many years.", "A baby elephant is called a calf and can weigh over 200 pounds at birth."],
    funFact: "Elephants are one of the few animals that can recognize themselves in a mirror." },
  { name: "Giraffe", category: "animals", emoji: "🦒",
    simpleFact: "The giraffe is the tallest animal in the world.",
    facts: ["A giraffe's neck alone can be six feet long.", "Giraffes only sleep about 30 minutes to 2 hours a day.", "Every giraffe has a unique pattern of spots, just like a human fingerprint."],
    funFact: "A giraffe's tongue can be up to 20 inches (50 cm) long!" },
  { name: "Tiger", category: "animals", emoji: "🐯",
    simpleFact: "Tigers are the largest wild cats in the world.",
    facts: ["Every tiger has a unique stripe pattern, like a fingerprint.", "Tigers are strong swimmers and love water, unlike most cats.", "A tiger's roar can be heard almost two miles away."],
    funFact: "A tiger's stripes are actually on its skin, not just its fur." },
  { name: "Panda", category: "animals", emoji: "🐼",
    simpleFact: "Giant pandas eat mostly bamboo, up to 12 hours a day.",
    facts: ["Pandas can eat 20-40 pounds of bamboo every single day.", "A newborn panda cub is tiny — about the size of a stick of butter.", "Pandas have a special wrist bone that works like a thumb to hold bamboo."],
    funFact: "Despite eating mostly plants, a panda's digestive system is built like a meat-eater's." },
  { name: "Koala", category: "animals", emoji: "🐨",
    simpleFact: "Koalas live in Australia and eat mostly eucalyptus leaves.",
    facts: ["Koalas sleep up to 20 hours a day to save energy.", "Baby koalas are called joeys, just like baby kangaroos.", "Koalas rarely need to drink water because eucalyptus leaves are full of moisture."],
    funFact: "A koala's fingerprints are so similar to a human's that they can be hard to tell apart!" },
  { name: "Kangaroo", category: "animals", emoji: "🦘",
    simpleFact: "Kangaroos are famous for hopping and carrying their babies in a pouch.",
    facts: ["A group of kangaroos is called a mob.", "Kangaroos can hop as fast as 35 miles per hour.", "A baby kangaroo, called a joey, is tiny and blind when born."],
    funFact: "Kangaroos can't walk backwards!" },
  { name: "Wolf", category: "animals", emoji: "🐺",
    simpleFact: "Wolves live and hunt together in family groups called packs.",
    facts: ["A wolf pack usually has 6 to 10 members led by a parent pair.", "Wolves howl to communicate with their pack over long distances.", "Wolves are the ancestors of all pet dogs."],
    funFact: "A wolf's howl can be heard up to 6 miles away in the forest." },
  { name: "Fox", category: "animals", emoji: "🦊",
    simpleFact: "Foxes are clever animals known for their bushy tails and pointy ears.",
    facts: ["A fox's bushy tail helps it balance and stay warm in winter.", "Foxes have excellent hearing and can hear small animals moving underground.", "Most foxes are active at night and sleep during the day."],
    funFact: "Foxes can make over 40 different sounds to communicate!" },
  { name: "Owl", category: "animals", emoji: "🦉",
    simpleFact: "Owls are birds that can turn their heads almost all the way around.",
    facts: ["An owl can turn its head up to 270 degrees.", "Owls fly almost silently because of their special soft feathers.", "Most owls hunt at night using excellent hearing and eyesight."],
    funFact: "An owl can't move its eyes — that's why it turns its whole head instead!" },
  { name: "Eagle", category: "animals", emoji: "🦅",
    simpleFact: "Eagles are powerful birds with amazing eyesight.",
    facts: ["An eagle can spot a rabbit from almost two miles away.", "Eagles build huge nests, sometimes weighing over a thousand pounds.", "Eagles can fly at speeds over 30 miles per hour, and dive even faster."],
    funFact: "An eagle's eyesight is about four to eight times sharper than a human's." },
  { name: "Butterfly", category: "animals", emoji: "🦋",
    simpleFact: "Butterflies start life as caterpillars before transforming completely.",
    facts: ["This transformation is called metamorphosis.", "Butterflies taste with their feet.", "Some butterflies migrate thousands of miles, like the monarch butterfly."],
    funFact: "Monarch butterflies can travel up to 3,000 miles during migration." },
  { name: "Bee", category: "animals", emoji: "🐝",
    simpleFact: "Bees help flowers grow by carrying pollen from one to another.",
    facts: ["This is called pollination, and it helps plants make fruits and seeds.", "A single beehive can have up to 60,000 bees.", "Bees communicate the location of flowers by doing a special dance."],
    funFact: "A bee has to visit about 2 million flowers to make one pound of honey." },
  { name: "Chameleon", category: "animals", emoji: "🦎",
    simpleFact: "Chameleons are famous for changing the color of their skin.",
    facts: ["Chameleons change color to show their mood, not just to hide.", "Each of a chameleon's eyes can look in a different direction at the same time.", "A chameleon's tongue can be as long as its whole body."],
    funFact: "A chameleon's tongue can shoot out and catch an insect in a fraction of a second!" },
  { name: "Penguin", category: "animals", emoji: "🐧",
    simpleFact: "Penguins are birds that can't fly, but they are excellent swimmers.",
    facts: ["Penguins use their wings like flippers to swim through water.", "Emperor penguins can dive deeper than 500 meters.", "Most penguins live in the Southern Hemisphere, especially Antarctica."],
    funFact: "Some penguins can swim as fast as 22 miles per hour!" },

  // ============ SPACE & PLANETS ============
  { name: "The Sun", category: "space", emoji: "☀️",
    simpleFact: "The Sun is a giant star that gives Earth light and heat.",
    facts: ["The Sun is so big that over one million Earths could fit inside it.", "Light from the Sun takes about 8 minutes to reach Earth.", "The Sun is made mostly of hydrogen and helium gas."],
    funFact: "The Sun is actually a star, just like the ones you see at night — it's only closer!" },
  { name: "Mercury", category: "space", emoji: "🪐",
    simpleFact: "Mercury is the closest planet to the Sun.",
    facts: ["A year on Mercury is only 88 Earth days long.", "Mercury has huge temperature swings — very hot in the day, very cold at night.", "Mercury is the smallest planet in our solar system."],
    funFact: "Mercury has no moons at all." },
  { name: "Venus", category: "space", emoji: "🌕",
    simpleFact: "Venus is the hottest planet in our solar system.",
    facts: ["Venus is covered in thick clouds that trap heat.", "A day on Venus is longer than its year.", "Venus is often called Earth's twin because it's a similar size."],
    funFact: "Venus spins backward compared to most other planets." },
  { name: "Earth", category: "space", emoji: "🌍",
    simpleFact: "Earth is the only planet we know of that has life.",
    facts: ["About 71% of Earth's surface is covered in water.", "Earth takes 365 days to travel around the Sun.", "Earth has one moon, which affects our ocean tides."],
    funFact: "Earth is the only planet in our solar system not named after a Greek or Roman god." },
  { name: "Mars", category: "space", emoji: "🔴",
    simpleFact: "Mars is called the Red Planet because of its rusty red color.",
    facts: ["Mars has the largest volcano in the solar system, called Olympus Mons.", "A day on Mars is about 24 hours and 37 minutes — close to Earth's.", "Scientists have sent robots called rovers to explore Mars."],
    funFact: "Mars has two small moons named Phobos and Deimos." },
  { name: "Jupiter", category: "space", emoji: "🟠",
    simpleFact: "Jupiter is the biggest planet in our solar system.",
    facts: ["Jupiter has a giant storm called the Great Red Spot that's bigger than Earth.", "Jupiter has more than 100 known moons, and astronomers keep finding more.", "Jupiter is made mostly of gas, with no solid surface to stand on."],
    funFact: "Jupiter is so big that all the other planets could fit inside it." },
  { name: "Saturn", category: "space", emoji: "🪐",
    simpleFact: "Saturn is famous for its beautiful rings made of ice and rock.",
    facts: ["Saturn's rings are made of billions of pieces of ice and rock.", "Saturn is the least dense planet — it would float in water!", "Saturn has more known moons than any other planet, with new ones still being discovered."],
    funFact: "Saturn's largest moon, Titan, has lakes made of liquid methane." },
  { name: "Uranus", category: "space", emoji: "🔵",
    simpleFact: "Uranus is an icy blue planet that spins on its side.",
    facts: ["Uranus rotates on its side, unlike any other planet.", "Uranus is made of water, methane, and ammonia ices.", "A year on Uranus lasts 84 Earth years."],
    funFact: "Uranus was the first planet discovered using a telescope, in 1781." },
  { name: "Neptune", category: "space", emoji: "🔷",
    simpleFact: "Neptune is the farthest planet from the Sun.",
    facts: ["Neptune has the strongest winds in the solar system.", "Neptune takes 165 Earth years to orbit the Sun once.", "Neptune was discovered using math before it was ever seen through a telescope."],
    funFact: "Neptune's winds can blow faster than the speed of sound!" },
  { name: "The Moon", category: "space", emoji: "🌙",
    simpleFact: "The Moon is Earth's only natural satellite.",
    facts: ["The Moon causes ocean tides on Earth.", "Astronauts first walked on the Moon in 1969.", "The Moon is slowly moving away from Earth every year."],
    funFact: "The same side of the Moon always faces Earth." },
  { name: "Stars", category: "space", emoji: "⭐",
    simpleFact: "Stars are giant balls of burning gas far away in space.",
    facts: ["The closest star to Earth (besides the Sun) is over 4 light-years away.", "Stars come in many colors depending on their temperature.", "Some stars are so far away their light takes thousands of years to reach us."],
    funFact: "When you look at a distant star, you're seeing light that left it a very long time ago." },
  { name: "The Milky Way", category: "space", emoji: "🌌",
    simpleFact: "The Milky Way is the galaxy that contains our solar system.",
    facts: ["The Milky Way has more than 100 billion stars.", "Our solar system is just a tiny part of the Milky Way.", "The Milky Way is shaped like a giant spinning spiral."],
    funFact: "It would take about 100,000 years to travel across the Milky Way at the speed of light." },
  { name: "Astronaut", category: "space", emoji: "🧑‍🚀",
    simpleFact: "An astronaut is a person trained to travel and work in space.",
    facts: ["Astronauts train for years before going to space.", "In space, astronauts float because there's very little gravity.", "Astronauts on the International Space Station orbit Earth about every 90 minutes."],
    funFact: "Astronauts can grow up to two inches taller in space because their spine stretches out!" },
  { name: "Rocket", category: "space", emoji: "🚀",
    simpleFact: "A rocket is a vehicle powerful enough to launch into space.",
    facts: ["Rockets need to reach a very high speed to escape Earth's gravity.", "Some rockets can be reused for multiple launches.", "Rockets carry astronauts, satellites, and supplies into space."],
    funFact: "A rocket must reach about 25,000 miles per hour to leave Earth's gravity completely." },
  { name: "Black Hole", category: "space", emoji: "🕳️",
    simpleFact: "A black hole is a place in space where gravity is so strong that nothing can escape, not even light.",
    facts: ["Black holes form when massive stars collapse at the end of their life.", "We can't see a black hole directly, but scientists can detect its effects on nearby matter.", "The nearest known black hole is thousands of light-years away."],
    funFact: "The first-ever photo of a black hole was taken in 2019." },

  // ============ DINOSAURS & PREHISTORIC LIFE ============
  { name: "Tyrannosaurus Rex", category: "dinosaurs", emoji: "🦖",
    simpleFact: "T. Rex was one of the largest meat-eating dinosaurs ever.",
    facts: ["T. Rex had teeth up to 12 inches long, including the root.", "Despite its size, T. Rex had surprisingly small arms.", "T. Rex lived about 68 to 66 million years ago."],
    funFact: "T. Rex's bite force was one of the strongest of any land animal ever." },
  { name: "Triceratops", category: "dinosaurs", emoji: "🦕",
    simpleFact: "Triceratops had three horns on its face and a large bony frill.",
    facts: ["Triceratops was a plant-eater, unlike T. Rex.", "Its name means 'three-horned face.'", "Triceratops could grow up to 30 feet long."],
    funFact: "Triceratops's frill may have helped protect its neck from predators." },
  { name: "Stegosaurus", category: "dinosaurs", emoji: "🦕",
    simpleFact: "Stegosaurus had large bony plates along its back and spikes on its tail.",
    facts: ["The plates on its back may have helped control its body temperature.", "Stegosaurus had a brain about the size of a walnut.", "It used the spikes on its tail to defend against predators."],
    funFact: "Stegosaurus lived over 65 million years before T. Rex existed!" },
  { name: "Velociraptor", category: "dinosaurs", emoji: "🦖",
    simpleFact: "Velociraptor was a small, fast, feathered dinosaur.",
    facts: ["Real velociraptors were only about the size of a turkey.", "Scientists believe velociraptors were covered in feathers.", "Velociraptor had a large curved claw on each foot."],
    funFact: "Velociraptor was much smaller in real life than movies usually show it!" },
  { name: "Brachiosaurus", category: "dinosaurs", emoji: "🦕",
    simpleFact: "Brachiosaurus was a giant, long-necked plant-eating dinosaur.",
    facts: ["Its front legs were longer than its back legs, unlike most dinosaurs.", "Brachiosaurus could reach leaves nearly 40 feet high.", "It was one of the tallest dinosaurs ever discovered."],
    funFact: "Brachiosaurus may have weighed as much as 10 elephants." },
  { name: "Pterodactyl", category: "dinosaurs", emoji: "🦅",
    simpleFact: "Pterodactyls were flying reptiles that lived alongside the dinosaurs.",
    facts: ["Pterodactyls were not technically dinosaurs — they were flying reptiles.", "Some pterodactyls had wingspans over 30 feet wide.", "They had light, hollow bones to help them fly."],
    funFact: "Some pterodactyls were as large as small airplanes!" },
  { name: "Ankylosaurus", category: "dinosaurs", emoji: "🦕",
    simpleFact: "Ankylosaurus was covered in thick armor and had a club-like tail.",
    facts: ["Its body was covered in bony plates like a suit of armor.", "The bony club at the end of its tail could smash a predator's legs.", "Ankylosaurus was a slow-moving plant-eater."],
    funFact: "Ankylosaurus's armor was so tough that few predators could bite through it." },
  { name: "Spinosaurus", category: "dinosaurs", emoji: "🦖",
    simpleFact: "Spinosaurus had a huge sail-like fin on its back and may have hunted in water.",
    facts: ["It's considered the largest known meat-eating dinosaur, even bigger than T. Rex.", "Scientists think Spinosaurus was a strong swimmer.", "Its sail may have been used to attract mates or control temperature."],
    funFact: "Spinosaurus is the only known dinosaur believed to have swum regularly." },
  { name: "Diplodocus", category: "dinosaurs", emoji: "🦕",
    simpleFact: "Diplodocus had one of the longest necks and tails of any dinosaur.",
    facts: ["Diplodocus could grow up to 90 feet long, mostly neck and tail.", "It used its long tail like a whip, possibly for defense.", "It ate plants using its peg-like teeth."],
    funFact: "Diplodocus's tail alone could be longer than a school bus." },
  { name: "Allosaurus", category: "dinosaurs", emoji: "🦖",
    simpleFact: "Allosaurus was a fierce predator that lived before T. Rex.",
    facts: ["Allosaurus lived about 155 to 145 million years ago.", "It had sharp, curved teeth for tearing meat.", "Allosaurus may have hunted in groups."],
    funFact: "Allosaurus lived nearly 80 million years before Tyrannosaurus Rex." },
  { name: "Woolly Mammoth", category: "dinosaurs", emoji: "🦣",
    simpleFact: "Woolly mammoths were giant, furry relatives of today's elephants.",
    facts: ["They lived during the Ice Age and had thick fur to stay warm.", "Mammoths had curved tusks that could grow over 13 feet long.", "Woolly mammoths went extinct around 4,000 years ago."],
    funFact: "Some frozen woolly mammoths have been found so well preserved that scientists could see their last meal." },
  { name: "Saber-Tooth Tiger", category: "dinosaurs", emoji: "🐅",
    simpleFact: "The saber-tooth tiger was an Ice Age predator with huge curved teeth.",
    facts: ["Its canine teeth could grow up to 7 inches long.", "It wasn't actually closely related to modern tigers.", "It likely hunted large Ice Age mammals like bison and young mammoths."],
    funFact: "Saber-tooth cats' famous teeth were actually quite fragile and could break easily." },
  { name: "Fossil", category: "dinosaurs", emoji: "🦴",
    simpleFact: "A fossil is the preserved remains or trace of an ancient living thing.",
    facts: ["Fossils form over millions of years, usually in rock or sediment.", "Fossils can be bones, footprints, or even ancient plants.", "Scientists study fossils to learn what ancient life looked like."],
    funFact: "Some fossils are so detailed you can see the texture of ancient skin or feathers." },
  { name: "Paleontologist", category: "dinosaurs", emoji: "⛏️",
    simpleFact: "A paleontologist is a scientist who studies fossils and ancient life.",
    facts: ["Paleontologists carefully dig up fossils without damaging them.", "They use tools like brushes and small picks to uncover bones.", "Paleontology helps us understand how life on Earth has changed over time."],
    funFact: "Some famous dinosaur fossils took years of careful digging to fully uncover." },
  { name: "Extinction", category: "dinosaurs", emoji: "☄️",
    simpleFact: "Extinction is when every member of a species has died out forever.",
    facts: ["Most dinosaurs went extinct about 66 million years ago.", "Scientists believe a giant asteroid impact caused this mass extinction.", "Not all ancient life went extinct — birds are actually living descendants of dinosaurs."],
    funFact: "Many scientists consider birds to be modern-day dinosaurs!" },

  // ============ COUNTRIES & GEOGRAPHY ============
  { name: "United States", category: "countries", emoji: "🇺🇸",
    simpleFact: "The United States is a large country in North America made up of 50 states.",
    facts: ["The capital city is Washington, D.C.", "The United States has coastlines on both the Atlantic and Pacific Oceans.", "It's home to famous landmarks like the Grand Canyon and the Statue of Liberty."],
    funFact: "Alaska, a U.S. state, is so big it could fit Texas inside it more than twice." },
  { name: "Canada", category: "countries", emoji: "🇨🇦",
    simpleFact: "Canada is the second-largest country in the world by area.",
    facts: ["The capital city is Ottawa.", "Canada has more lakes than any other country in the world.", "Canada shares the longest border in the world with the United States."],
    funFact: "Canada has two official languages: English and French." },
  { name: "Brazil", category: "countries", emoji: "🇧🇷",
    simpleFact: "Brazil is the largest country in South America.",
    facts: ["The capital city is Brasília.", "Most of the Amazon Rainforest is located in Brazil.", "Portuguese is the main language spoken in Brazil."],
    funFact: "Brazil is the only country in South America where Portuguese is the official language." },
  { name: "United Kingdom", category: "countries", emoji: "🇬🇧",
    simpleFact: "The United Kingdom is made up of England, Scotland, Wales, and Northern Ireland.",
    facts: ["The capital city is London.", "The UK is home to famous landmarks like Big Ben and Stonehenge.", "The UK is an island nation surrounded by the sea."],
    funFact: "The London Underground, opened in 1863, was the world's first subway system." },
  { name: "France", category: "countries", emoji: "🇫🇷",
    simpleFact: "France is a country in Western Europe famous for the Eiffel Tower.",
    facts: ["The capital city is Paris.", "France is one of the most visited countries in the world.", "French is the official language spoken there."],
    funFact: "The Eiffel Tower grows about 6 inches taller in the summer heat!" },
  { name: "Egypt", category: "countries", emoji: "🇪🇬",
    simpleFact: "Egypt is famous for its ancient pyramids and the Nile River.",
    facts: ["The capital city is Cairo.", "The Great Pyramid of Giza is one of the oldest structures still standing today.", "The Nile River is one of the longest rivers in the world."],
    funFact: "The Great Pyramid of Giza was the tallest man-made structure in the world for over 3,800 years." },
  { name: "Kenya", category: "countries", emoji: "🇰🇪",
    simpleFact: "Kenya is a country in East Africa known for its wildlife and savannas.",
    facts: ["The capital city is Nairobi.", "Kenya is home to Mount Kenya, the second-tallest mountain in Africa.", "Millions of wildebeest migrate across Kenya's plains every year."],
    funFact: "Kenya's Great Migration is one of the largest animal migrations on Earth." },
  { name: "India", category: "countries", emoji: "🇮🇳",
    simpleFact: "India is one of the most populated countries in the world.",
    facts: ["The capital city is New Delhi.", "India is home to the Taj Mahal, a famous white marble monument.", "India has 22 officially recognized languages."],
    funFact: "India is the birthplace of chess, which was originally called chaturanga." },
  { name: "China", category: "countries", emoji: "🇨🇳",
    simpleFact: "China is the most populated country in the world.",
    facts: ["The capital city is Beijing.", "The Great Wall of China stretches for thousands of miles.", "China has one of the oldest continuous civilizations in history."],
    funFact: "The Great Wall of China is so long it would stretch almost around the Earth if straightened out." },
  { name: "Japan", category: "countries", emoji: "🇯🇵",
    simpleFact: "Japan is an island country in East Asia known for its technology and culture.",
    facts: ["The capital city is Tokyo.", "Japan is made up of thousands of islands.", "Japan has super-fast trains called bullet trains."],
    funFact: "Japan's bullet trains can travel over 200 miles per hour." },
  { name: "Australia", category: "countries", emoji: "🇦🇺",
    simpleFact: "Australia is both a country and a continent, home to unique animals like kangaroos.",
    facts: ["The capital city is Canberra.", "Australia is home to the Great Barrier Reef, the largest coral reef system.", "Most of Australia's animals, like kangaroos and koalas, live nowhere else naturally."],
    funFact: "The Great Barrier Reef is so large it can be seen from space." },
  { name: "Antarctica", category: "countries", emoji: "🐧",
    simpleFact: "Antarctica is the coldest continent on Earth, covered almost entirely in ice.",
    facts: ["No country owns Antarctica — it's used for scientific research.", "Antarctica is the driest continent, even though it's covered in ice.", "Penguins are among the few animals that live there."],
    funFact: "Antarctica holds about 70% of the world's fresh water, frozen in ice." },
  { name: "Mount Everest", category: "countries", emoji: "🏔️",
    simpleFact: "Mount Everest is the tallest mountain on Earth.",
    facts: ["It's located in the Himalayas, on the border of Nepal and Tibet.", "Mount Everest stands about 29,032 feet tall.", "Climbing Mount Everest is extremely difficult and dangerous."],
    funFact: "The top of Mount Everest is so high that climbers often need extra oxygen to breathe." },
  { name: "The Amazon Rainforest", category: "countries", emoji: "🌳",
    simpleFact: "The Amazon Rainforest is the largest tropical rainforest in the world.",
    facts: ["It's home to about 10% of all known species on Earth.", "The Amazon River, which runs through it, carries more water than any other river.", "The rainforest produces a large amount of the world's oxygen."],
    funFact: "Scientists believe there are still thousands of undiscovered species living in the Amazon." },
  { name: "The Sahara Desert", category: "countries", emoji: "🏜️",
    simpleFact: "The Sahara is the largest hot desert in the world.",
    facts: ["It covers most of North Africa, almost as large as the United States.", "Temperatures can be extremely hot during the day and cold at night.", "Despite being a desert, the Sahara has occasional oases with water and plants."],
    funFact: "The Sahara Desert is almost as big as the entire United States." },

  // ============ HUMAN BODY ============
  { name: "Heart", category: "human-body", emoji: "🫀",
    simpleFact: "Your heart pumps blood all around your body.",
    facts: ["An adult heart beats about 100,000 times a day.", "The heart has four chambers that work together to pump blood.", "Blood carries oxygen and nutrients to every part of your body."],
    funFact: "Your heart beats about 35 million times every year!" },
  { name: "Brain", category: "human-body", emoji: "🧠",
    simpleFact: "Your brain controls everything your body does, from thinking to moving.",
    facts: ["The brain has billions of nerve cells called neurons.", "Your brain uses about 20% of your body's energy.", "Different parts of the brain control different jobs, like memory and movement."],
    funFact: "Your brain generates enough electricity to power a small light bulb." },
  { name: "Lungs", category: "human-body", emoji: "🫁",
    simpleFact: "Your lungs help you breathe in oxygen and breathe out carbon dioxide.",
    facts: ["You have two lungs, and the right one is slightly bigger than the left.", "Lungs are full of tiny air sacs that absorb oxygen into your blood.", "You breathe about 20,000 times a day without even thinking about it."],
    funFact: "If you unfolded all the air sacs in your lungs, they would cover an area the size of a tennis court!" },
  { name: "Skeleton", category: "human-body", emoji: "🦴",
    simpleFact: "Your skeleton is made of bones that support and protect your body.",
    facts: ["Adults have 206 bones in their body.", "Babies are actually born with about 300 bones, which fuse together over time.", "The femur, in your thigh, is the longest and strongest bone."],
    funFact: "Bones are about five times stronger than steel of the same weight." },
  { name: "Muscles", category: "human-body", emoji: "💪",
    simpleFact: "Muscles help you move by pulling on your bones.",
    facts: ["Your body has over 600 muscles.", "The strongest muscle for its size is the jaw muscle, used for biting.", "Muscles work in pairs, with one pulling while the other relaxes."],
    funFact: "It takes about 200 muscles to take just one step." },
  { name: "Stomach", category: "human-body", emoji: "🫃",
    simpleFact: "Your stomach breaks down the food you eat so your body can use it.",
    facts: ["The stomach uses strong acid to help digest food.", "Food usually stays in the stomach for a few hours before moving on.", "Your stomach can stretch to hold a large meal."],
    funFact: "Your stomach lining replaces itself every few days so the acid doesn't hurt it." },
  { name: "Eyes", category: "human-body", emoji: "👀",
    simpleFact: "Your eyes let you see the world around you.",
    facts: ["Eyes work like a camera, focusing light to create images.", "Your eyes can distinguish about 10 million different colors.", "You blink about 15-20 times every minute."],
    funFact: "Your eyes start developing just two weeks after you're conceived." },
  { name: "Ears", category: "human-body", emoji: "👂",
    simpleFact: "Your ears let you hear sounds and also help you keep your balance.",
    facts: ["Sound waves travel through your ear and turn into signals your brain understands.", "Your inner ear also helps you stay balanced when you move.", "Ears never stop growing throughout your whole life."],
    funFact: "Your ears help you balance even more than they help you hear!" },
  { name: "Skin", category: "human-body", emoji: "🤚",
    simpleFact: "Skin is the largest organ in your body and protects everything inside.",
    facts: ["Skin protects your body from germs and injury.", "Skin helps control your body temperature through sweating.", "Your skin completely replaces itself about once a month."],
    funFact: "If you spread out an adult's skin, it would cover about 20 square feet." },
  { name: "Teeth", category: "human-body", emoji: "🦷",
    simpleFact: "Teeth help you chew food and are covered in the hardest substance in your body.",
    facts: ["Adults usually have 32 teeth, including wisdom teeth.", "Tooth enamel is the hardest substance in the human body.", "Children have 20 baby teeth before their adult teeth grow in."],
    funFact: "Tooth enamel is harder than any bone in your body." },
  { name: "Blood", category: "human-body", emoji: "🩸",
    simpleFact: "Blood carries oxygen and nutrients to every part of your body.",
    facts: ["An adult body has about 5 liters of blood.", "Red blood cells carry oxygen, and white blood cells fight germs.", "Your body makes new blood cells constantly in your bone marrow."],
    funFact: "Your blood travels about 12,000 miles through your body every single day." },
  { name: "Kidneys", category: "human-body", emoji: "🫘",
    simpleFact: "Your kidneys clean your blood and remove waste from your body.",
    facts: ["You have two kidneys, and you can actually live with just one.", "Kidneys filter about 50 gallons of blood every day.", "Kidneys help control the balance of water in your body."],
    funFact: "Your kidneys filter your entire blood supply about 40 times a day." },
  { name: "Liver", category: "human-body", emoji: "🫀",
    simpleFact: "The liver cleans your blood and helps digest food.",
    facts: ["The liver is the largest internal organ in your body.", "It helps break down fats from the food you eat.", "The liver can regenerate itself even if part of it is removed."],
    funFact: "The liver can regrow to its full size even if up to 70% of it is removed." },
  { name: "Nervous System", category: "human-body", emoji: "⚡",
    simpleFact: "Your nervous system sends messages between your brain and the rest of your body.",
    facts: ["It includes your brain, spinal cord, and nerves throughout your body.", "Nerve signals can travel as fast as 268 miles per hour.", "Your nervous system controls both things you choose to do and things that happen automatically."],
    funFact: "Some nerve signals travel through your body faster than a race car!" },
  { name: "Immune System", category: "human-body", emoji: "🛡️",
    simpleFact: "Your immune system protects your body from germs that could make you sick.",
    facts: ["White blood cells are a key part of your immune system.", "Your immune system can remember germs it has fought before.", "This memory is part of why vaccines and past illnesses can protect you in the future."],
    funFact: "Your immune system can recognize and remember millions of different germs." },

  // ============ OCEAN & SEA LIFE ============
  { name: "Dolphin", category: "ocean", emoji: "🐬",
    simpleFact: "Dolphins are intelligent sea mammals known for being playful.",
    facts: ["Dolphins use sound waves called echolocation to find food and navigate.", "Dolphins are mammals, so they breathe air and can't breathe underwater.", "Dolphins often live and hunt together in groups called pods."],
    funFact: "Dolphins can recognize themselves in a mirror, a rare sign of self-awareness." },
  { name: "Shark", category: "ocean", emoji: "🦈",
    simpleFact: "Sharks are powerful fish that have existed for hundreds of millions of years.",
    facts: ["Sharks have existed longer than dinosaurs.", "A shark can replace a lost tooth in as little as one day.", "Most sharks are not dangerous to humans at all."],
    funFact: "Sharks have been around for over 400 million years — long before dinosaurs existed." },
  { name: "Octopus", category: "ocean", emoji: "🐙",
    simpleFact: "Octopuses are smart sea animals with eight arms and no bones.",
    facts: ["An octopus has three hearts.", "Octopuses can change the color and texture of their skin to hide.", "They are considered one of the most intelligent invertebrates."],
    funFact: "An octopus has three hearts and blue blood!" },
  { name: "Whale", category: "ocean", emoji: "🐋",
    simpleFact: "Whales are the largest animals to have ever lived on Earth.",
    facts: ["The blue whale is the largest animal ever known to exist.", "Whales are mammals and must come to the surface to breathe air.", "Some whales sing songs that can travel for miles underwater."],
    funFact: "A blue whale's heart alone can weigh as much as a small car." },
  { name: "Sea Turtle", category: "ocean", emoji: "🐢",
    simpleFact: "Sea turtles have lived in the oceans for over 100 million years.",
    facts: ["Sea turtles can hold their breath for hours while resting.", "Female sea turtles return to the same beach where they were born to lay eggs.", "Sea turtles can travel thousands of miles across the ocean."],
    funFact: "Sea turtles have existed since the age of the dinosaurs." },
  { name: "Starfish", category: "ocean", emoji: "⭐",
    simpleFact: "Starfish, also called sea stars, can regrow lost arms.",
    facts: ["Most starfish have five arms, but some have many more.", "A starfish doesn't have a brain, but it can still sense light and touch.", "Starfish push their stomach outside their body to eat their prey."],
    funFact: "Some starfish can regrow an entire new body from just one arm." },
  { name: "Jellyfish", category: "ocean", emoji: "🪼",
    simpleFact: "Jellyfish are ancient sea creatures made mostly of water.",
    facts: ["Jellyfish have no brain, heart, or bones.", "Jellyfish are about 95% water.", "Jellyfish have existed for more than 500 million years."],
    funFact: "Jellyfish are older than dinosaurs, sharks, and even trees!" },
  { name: "Crab", category: "ocean", emoji: "🦀",
    simpleFact: "Crabs are sea creatures known for walking sideways.",
    facts: ["Crabs have a hard outer shell called an exoskeleton.", "Crabs must shed their shell to grow bigger, a process called molting.", "Most crabs walk sideways because of how their legs are built."],
    funFact: "There are over 4,500 known species of crab around the world." },
  { name: "Seahorse", category: "ocean", emoji: "🐠",
    simpleFact: "Seahorses are unusual fish where the male carries the babies.",
    facts: ["Male seahorses carry the eggs in a pouch until they hatch.", "Seahorses swim upright, unlike most fish.", "A seahorse can move each eye independently to look in two directions."],
    funFact: "Seahorses are the only animal species where the males give birth!" },
  { name: "Coral Reef", category: "ocean", emoji: "🪸",
    simpleFact: "Coral reefs are colorful underwater structures built by tiny living animals.",
    facts: ["Coral reefs are built by tiny animals called coral polyps.", "Reefs provide homes for about 25% of all ocean species.", "Coral reefs can take thousands of years to fully form."],
    funFact: "Even though they look like plants or rocks, corals are actually tiny living animals." },
  { name: "Clownfish", category: "ocean", emoji: "🐠",
    simpleFact: "Clownfish live safely among sea anemones, which protect them from predators.",
    facts: ["Clownfish are immune to the sting of the anemones they live in.", "All clownfish are born male and can change into females later in life.", "Clownfish and anemones help protect each other."],
    funFact: "Every clownfish is born male, and some later change into females." },
  { name: "Stingray", category: "ocean", emoji: "🐟",
    simpleFact: "Stingrays are flat sea fish related to sharks, with a stinger on their tail.",
    facts: ["Stingrays are closely related to sharks.", "They glide through water by flapping their wide, flat fins.", "Stingrays usually only sting when they feel threatened."],
    funFact: "Stingrays can sense the electric fields of other animals to find food buried in sand." },
  { name: "Sea Otter", category: "ocean", emoji: "🦦",
    simpleFact: "Sea otters float on their backs and use rocks as tools to open shells.",
    facts: ["Sea otters have the thickest fur of any animal to stay warm.", "They use rocks as tools to crack open shellfish.", "Sea otters often hold hands while sleeping so they don't drift apart."],
    funFact: "Sea otters hold hands while sleeping so the ocean current doesn't separate them!" },
  { name: "Squid", category: "ocean", emoji: "🦑",
    simpleFact: "Squid are fast-swimming sea creatures with eight arms and two long tentacles.",
    facts: ["Squid can shoot ink to escape from predators.", "Some giant squid can grow up to 43 feet long.", "Squid move quickly through water by shooting jets of water."],
    funFact: "The giant squid has the largest eyes of any animal on Earth." },
  { name: "The Deep Sea", category: "ocean", emoji: "🌊",
    simpleFact: "The deep sea is the darkest, least explored part of the ocean.",
    facts: ["Sunlight can't reach most of the deep sea, so it's completely dark.", "Some deep sea creatures make their own light, called bioluminescence.", "Humans have explored less of the deep ocean than the surface of the Moon."],
    funFact: "We have mapped more of the surface of Mars than the bottom of our own oceans." },

  // ============ WEATHER & SEASONS ============
  { name: "Rain", category: "weather", emoji: "🌧️",
    simpleFact: "Rain happens when water droplets in clouds get too heavy and fall to the ground.",
    facts: ["Rain is part of the water cycle, which moves water between the sky and the ground.", "Raindrops are usually shaped more like tiny hamburger buns than teardrops.", "Some places on Earth almost never get rain, while others get rain nearly every day."],
    funFact: "The smell after rain has a name — it's called petrichor." },
  { name: "Snow", category: "weather", emoji: "❄️",
    simpleFact: "Snow forms when water freezes into ice crystals high in cold clouds.",
    facts: ["Every single snowflake has a unique six-sided pattern.", "Snow forms when the temperature in clouds is below freezing.", "Fresh snow is mostly trapped air, which is why it looks so bright and fluffy."],
    funFact: "No two snowflakes have ever been found to be exactly alike." },
  { name: "Thunder and Lightning", category: "weather", emoji: "⛈️",
    simpleFact: "Lightning is a giant spark of electricity, and thunder is the sound it makes.",
    facts: ["Lightning heats the air around it hotter than the surface of the Sun.", "Thunder is the sound made by air rapidly expanding after a lightning strike.", "You see lightning before you hear thunder because light travels faster than sound."],
    funFact: "You can estimate how far away a storm is by counting the seconds between lightning and thunder." },
  { name: "Rainbow", category: "weather", emoji: "🌈",
    simpleFact: "A rainbow appears when sunlight passes through raindrops and splits into colors.",
    facts: ["A rainbow always has red on the outer edge and violet on the inner edge.", "Rainbows appear opposite the Sun from where you're standing.", "You can sometimes see a rainbow in mist from a waterfall or garden hose."],
    funFact: "No two people ever see exactly the same rainbow — it depends on where you're standing!" },
  { name: "Clouds", category: "weather", emoji: "☁️",
    simpleFact: "Clouds are made of tiny water droplets or ice crystals floating in the sky.",
    facts: ["There are many types of clouds, from fluffy cumulus to flat stratus clouds.", "Clouds form when warm, moist air rises and cools.", "Some storm clouds can tower higher than Mount Everest."],
    funFact: "A single fluffy cumulus cloud can weigh over a million pounds, even though it floats." },
  { name: "Wind", category: "weather", emoji: "💨",
    simpleFact: "Wind is air moving from one place to another.",
    facts: ["Wind happens because warm air rises and cooler air rushes in to take its place.", "Wind can be gentle like a breeze or powerful like a hurricane.", "People use windmills and turbines to turn wind into electricity."],
    funFact: "The fastest wind gust ever recorded on Earth's surface was over 250 miles per hour." },
  { name: "Hurricane", category: "weather", emoji: "🌀",
    simpleFact: "A hurricane is a massive, spinning storm that forms over warm ocean water.",
    facts: ["Hurricanes have a calm center called the eye.", "Hurricanes get their energy from warm ocean water.", "The same type of storm is called a typhoon in some parts of the world."],
    funFact: "A hurricane can release as much energy in one day as thousands of nuclear bombs." },
  { name: "Tornado", category: "weather", emoji: "🌪️",
    simpleFact: "A tornado is a spinning column of air that reaches from a storm cloud to the ground.",
    facts: ["Tornadoes can have wind speeds over 300 miles per hour.", "The United States gets more tornadoes than any other country.", "Tornadoes usually last only a few minutes, but can cause serious damage."],
    funFact: "A tornado's wind can be strong enough to lift entire houses off the ground." },
  { name: "Spring", category: "weather", emoji: "🌷",
    simpleFact: "Spring is the season when plants start growing again after winter.",
    facts: ["Spring happens because Earth's tilt brings more sunlight to your hemisphere.", "Many animals wake up from hibernation in spring.", "Flowers and trees often bloom during spring."],
    funFact: "In spring, some places can experience all four seasons' weather in a single week!" },
  { name: "Summer", category: "weather", emoji: "☀️",
    simpleFact: "Summer is the warmest season, with the longest days of the year.",
    facts: ["The longest day of the year, called the summer solstice, happens in summer.", "Summer happens when your hemisphere is tilted closest to the Sun.", "Many places get the least rain during summer."],
    funFact: "On the summer solstice, some places near the North Pole get 24 hours of daylight." },
  { name: "Fall", category: "weather", emoji: "🍂",
    simpleFact: "Fall, also called autumn, is when leaves change color and temperatures cool down.",
    facts: ["Leaves change color because trees stop making green chlorophyll.", "Many animals prepare for winter by storing food in fall.", "Fall is also harvest season for many crops."],
    funFact: "The bright colors in fall leaves — orange and yellow — are actually there all year, just hidden by green." },
  { name: "Winter", category: "weather", emoji: "⛄",
    simpleFact: "Winter is the coldest season, with the shortest days of the year.",
    facts: ["Winter happens when your hemisphere is tilted away from the Sun.", "Some animals hibernate, or sleep through most of winter.", "The shortest day of the year, the winter solstice, happens in winter."],
    funFact: "When it's winter in the Northern Hemisphere, it's summer in the Southern Hemisphere!" },
  { name: "Fog", category: "weather", emoji: "🌫️",
    simpleFact: "Fog is a cloud that forms very close to the ground.",
    facts: ["Fog forms when warm, moist air cools quickly near the ground.", "Fog can make it hard to see even a short distance ahead.", "Some coastal cities, like San Francisco, are famous for their fog."],
    funFact: "Fog is technically just a cloud that touches the ground instead of floating in the sky." },
  { name: "Hail", category: "weather", emoji: "🧊",
    simpleFact: "Hail is balls of ice that fall from strong thunderstorms.",
    facts: ["Hailstones form when raindrops are carried up and down inside a storm cloud repeatedly.", "Each trip up and down adds another icy layer, like an onion.", "Some hailstones can grow bigger than a baseball."],
    funFact: "The largest hailstone ever recorded in the U.S. was almost 8 inches across." },
  { name: "The Water Cycle", category: "weather", emoji: "🔄",
    simpleFact: "The water cycle is how water moves between the ocean, sky, and land.",
    facts: ["Water evaporates from oceans and lakes into the air.", "It forms clouds, then falls back down as rain or snow.", "This cycle has been repeating for billions of years."],
    funFact: "The water you drink today may have once been part of an ocean, a cloud, or even a dinosaur's drink!" },

  // ============ PLANTS & GROWING THINGS ============
  { name: "Seeds", category: "plants", emoji: "🌰",
    simpleFact: "A seed contains everything a new plant needs to start growing.",
    facts: ["Seeds can travel by wind, water, or animals to find new places to grow.", "Some seeds can stay alive for years before they sprout.", "Inside every seed is a tiny baby plant called an embryo."],
    funFact: "Scientists once grew a plant from a 2,000-year-old seed found in an ancient fortress!" },
  { name: "Roots", category: "plants", emoji: "🌾",
    simpleFact: "Roots anchor a plant in the ground and soak up water and nutrients.",
    facts: ["Roots grow downward and outward to find water and nutrients.", "Some roots, like carrots, store food for the plant.", "Tree roots can sometimes spread wider than the tree's branches."],
    funFact: "The roots of one giant tree can stretch out longer than a football field." },
  { name: "Leaves", category: "plants", emoji: "🍃",
    simpleFact: "Leaves capture sunlight and turn it into food for the plant.",
    facts: ["Leaves are usually green because of a substance called chlorophyll.", "Tiny holes in leaves let the plant breathe in and out.", "Leaves come in countless shapes and sizes across different plants."],
    funFact: "A single large tree can have hundreds of thousands of leaves." },
  { name: "Flowers", category: "plants", emoji: "🌸",
    simpleFact: "Flowers help plants make seeds so new plants can grow.",
    facts: ["Flowers attract bees and other pollinators with color and scent.", "Not all plants make flowers — ferns and mosses don't.", "Some flowers only bloom for a single day."],
    funFact: "The world's largest flower can grow to be three feet wide and smells like rotting meat!" },
  { name: "Trees", category: "plants", emoji: "🌳",
    simpleFact: "Trees are tall plants with a woody trunk that can live for hundreds of years.",
    facts: ["Trees produce oxygen that humans and animals need to breathe.", "The oldest trees on Earth are thousands of years old.", "A tree's rings can tell you how old it is."],
    funFact: "The oldest known tree in the world is over 4,800 years old." },
  { name: "Photosynthesis", category: "plants", emoji: "🌿",
    simpleFact: "Photosynthesis is how plants use sunlight to make their own food.",
    facts: ["Plants take in sunlight, water, and carbon dioxide to make food.", "Photosynthesis also releases oxygen into the air.", "This process happens mostly inside a plant's leaves."],
    funFact: "Without photosynthesis, there wouldn't be enough oxygen in the air for us to breathe." },
  { name: "Sunflower", category: "plants", emoji: "🌻",
    simpleFact: "Sunflowers are tall, bright flowers that can turn to follow the Sun.",
    facts: ["Young sunflowers slowly turn during the day to face the Sun.", "A sunflower head is actually made of thousands of tiny flowers.", "Sunflowers can grow taller than a full-grown adult."],
    funFact: "Some sunflowers have grown taller than 30 feet — as tall as a three-story building!" },
  { name: "Cactus", category: "plants", emoji: "🌵",
    simpleFact: "Cactuses are plants that store water in their thick stems to survive in the desert.",
    facts: ["Most cactuses have spines instead of leaves to save water.", "Cactuses can survive for months, even years, without rain.", "Some cactuses only bloom flowers once a year, sometimes only at night."],
    funFact: "A large cactus can store more than 200 gallons of water inside itself." },
  { name: "Venus Flytrap", category: "plants", emoji: "🪤",
    simpleFact: "The Venus flytrap is a plant that catches and eats insects.",
    facts: ["It snaps shut when an insect touches tiny hairs inside its leaves.", "It grows in soil that doesn't have many nutrients, so it eats bugs instead.", "It can take about a week to fully digest an insect."],
    funFact: "A Venus flytrap can count — it only snaps shut after its hairs are touched twice." },
  { name: "Fruit", category: "plants", emoji: "🍎",
    simpleFact: "Fruit is the part of a plant that holds its seeds, and it's often sweet to eat.",
    facts: ["Fruits grow from the flower of a plant after it's pollinated.", "Tomatoes, cucumbers, and peppers are technically fruits, not vegetables.", "Fruit helps spread a plant's seeds when animals eat it."],
    funFact: "Bananas are berries, but strawberries technically aren't!" },
  { name: "Vegetables", category: "plants", emoji: "🥕",
    simpleFact: "Vegetables are the parts of plants we eat that aren't sweet fruit — like roots, stems, or leaves.",
    facts: ["Carrots are roots, celery is a stem, and lettuce is leaves.", "Vegetables are packed with vitamins that help keep your body healthy.", "Some vegetables, like broccoli, are actually flower buds."],
    funFact: "Broccoli is actually a bunch of tiny, unopened flowers!" },
  { name: "Fungi", category: "plants", emoji: "🍄",
    simpleFact: "Mushrooms and other fungi aren't plants at all — they're their own kind of living thing.",
    facts: ["Fungi don't make their own food from sunlight like plants do.", "Most of a fungus lives underground as thread-like strands called mycelium.", "Some fungi help trees share nutrients underground."],
    funFact: "One giant fungus found in Oregon covers almost 4 square miles underground, making it one of the largest living things on Earth." },
  { name: "Pollination", category: "plants", emoji: "🌼",
    simpleFact: "Pollination is how plants move pollen to make seeds, often with help from bees.",
    facts: ["Bees, butterflies, and even bats can help pollinate flowers.", "Wind also pollinates many plants, like grasses.", "Without pollination, most plants couldn't make fruit or seeds."],
    funFact: "About one-third of the food we eat depends on animal pollinators like bees." },
  { name: "The Redwood Tree", category: "plants", emoji: "🌲",
    simpleFact: "Redwood trees are among the tallest living things on Earth.",
    facts: ["Some redwoods grow taller than a 30-story building.", "Redwoods can live for more than 2,000 years.", "Their thick bark helps protect them from fire."],
    funFact: "The tallest known redwood tree is taller than the Statue of Liberty." },
  { name: "Grass", category: "plants", emoji: "🌱",
    simpleFact: "Grass is one of the most common plants on Earth, covering fields and lawns everywhere.",
    facts: ["Grass grows from the bottom, which is why mowing doesn't hurt it.", "Many of the foods we eat, like wheat, rice, and corn, are actually grasses.", "Grasslands cover about a quarter of the Earth's land."],
    funFact: "Bamboo is a type of grass, and it's one of the fastest-growing plants on Earth." },

  // ============ INVENTIONS & TECHNOLOGY ============
  { name: "The Wheel", category: "inventions", emoji: "⚙️",
    simpleFact: "The wheel is one of the most important inventions in human history.",
    facts: ["Wheels were first used over 5,000 years ago.", "Wheels made it much easier to carry heavy loads and travel far.", "Early wheels were made of solid wood before spokes were invented."],
    funFact: "The wheel wasn't invented until thousands of years after humans started farming." },
  { name: "The Light Bulb", category: "inventions", emoji: "💡",
    simpleFact: "The light bulb lets us light up rooms with electricity instead of fire.",
    facts: ["Thomas Edison improved the light bulb to make it practical and long-lasting.", "Early light bulbs used a thin wire called a filament that glows when heated.", "Modern LED bulbs use much less energy than old-style bulbs."],
    funFact: "Edison tested thousands of materials before finding one that worked well for the filament." },
  { name: "The Telephone", category: "inventions", emoji: "☎️",
    simpleFact: "The telephone lets people talk to each other from far away.",
    facts: ["Alexander Graham Bell is credited with inventing the telephone in 1876.", "Early telephones needed operators to connect calls by hand.", "Telephones eventually led to the invention of cell phones."],
    funFact: "The first phone call ever made was Alexander Graham Bell asking his assistant to come help him." },
  { name: "The Airplane", category: "inventions", emoji: "✈️",
    simpleFact: "The airplane allows humans to fly through the sky.",
    facts: ["The Wright brothers flew the first successful airplane in 1903.", "Their first flight lasted only 12 seconds.", "Airplanes work by using wings to create lift as air flows over them."],
    funFact: "The Wright brothers' first flight covered less distance than the wingspan of a modern jumbo jet." },
  { name: "The Internet", category: "inventions", emoji: "🌐",
    simpleFact: "The internet connects computers all over the world so people can share information instantly.",
    facts: ["The internet began as a project connecting a few research computers.", "Today, billions of devices around the world are connected to the internet.", "The internet lets people send messages, watch videos, and learn new things instantly."],
    funFact: "The first message ever sent over the early internet crashed the system after only two letters!" },
  { name: "The Printing Press", category: "inventions", emoji: "🖨️",
    simpleFact: "The printing press made it possible to print many copies of books quickly.",
    facts: ["Johannes Gutenberg built one of the first printing presses in the 1400s.", "Before the printing press, books had to be copied by hand.", "The printing press helped more people learn to read."],
    funFact: "Before the printing press, a single hand-copied book could take a scribe a whole year to finish." },
  { name: "The Computer", category: "inventions", emoji: "💻",
    simpleFact: "Computers can store, process, and share huge amounts of information.",
    facts: ["Early computers were as big as entire rooms.", "Modern computers are millions of times faster than early ones.", "Computers work using a language of just two numbers: 0 and 1."],
    funFact: "An early computer called ENIAC weighed as much as several elephants, but a modern phone is far more powerful." },
  { name: "The Camera", category: "inventions", emoji: "📷",
    simpleFact: "Cameras capture images of the world so we can save and share memories.",
    facts: ["Early cameras needed several hours to take just one photo.", "Digital cameras store photos electronically instead of on film.", "Cameras work by letting light through a lens onto film or a sensor."],
    funFact: "The very first photograph ever taken required an exposure time of about eight hours." },
  { name: "The Automobile", category: "inventions", emoji: "🚗",
    simpleFact: "The automobile, or car, changed how people travel from place to place.",
    facts: ["Early cars were slower than horses and often broke down.", "Henry Ford made cars affordable for many more people by mass-producing them.", "Modern cars can run on gasoline, electricity, or both."],
    funFact: "Henry Ford's assembly line could build a car in about 93 minutes, much faster than before." },
  { name: "The Television", category: "inventions", emoji: "📺",
    simpleFact: "Television lets people watch moving pictures and sound broadcast from far away.",
    facts: ["Early televisions showed only black-and-white pictures.", "Color television became common in the 1960s.", "Modern TVs use digital signals instead of older analog ones."],
    funFact: "The very first televisions had screens smaller than a modern tablet." },
  { name: "Robots", category: "inventions", emoji: "🤖",
    simpleFact: "Robots are machines that can be programmed to do tasks automatically.",
    facts: ["Robots are used in factories, hospitals, and even space exploration.", "Some robots can learn and adapt using artificial intelligence.", "The word 'robot' comes from a play written in 1920."],
    funFact: "Robots have been sent to explore other planets, like the rovers on Mars." },
  { name: "Solar Panels", category: "inventions", emoji: "☀️",
    simpleFact: "Solar panels turn sunlight into electricity.",
    facts: ["Solar panels are made of materials that release electricity when hit by light.", "Solar energy is a renewable resource that doesn't run out.", "Solar panels can be used on rooftops, in fields, and even in space."],
    funFact: "The International Space Station is powered by giant solar panels." },
  { name: "The Compass", category: "inventions", emoji: "🧭",
    simpleFact: "A compass is a tool that always points north, helping people find their way.",
    facts: ["Compasses use a magnetic needle that lines up with Earth's magnetic field.", "The compass was invented in ancient China.", "Sailors used compasses to navigate the open ocean long before satellites existed."],
    funFact: "Before the compass, sailors had to navigate using only the stars and coastlines." },
  { name: "3D Printing", category: "inventions", emoji: "🖨️",
    simpleFact: "3D printing builds solid objects layer by layer from a digital design.",
    facts: ["3D printers can make toys, tools, and even parts for machines.", "Some 3D printers can even print with materials that later become food or medicine.", "3D printing is sometimes used to make replacement parts for the human body."],
    funFact: "Doctors have used 3D printing to create custom prosthetic hands for children." },
  { name: "The Smartphone", category: "inventions", emoji: "📱",
    simpleFact: "A smartphone combines a phone, computer, and camera into one small device.",
    facts: ["Smartphones can access the internet, take photos, and run thousands of apps.", "The first modern smartphones appeared in the late 2000s.", "Many smartphones today are more powerful than computers from just a decade ago."],
    funFact: "Modern smartphones have far more computing power than the computers that helped land astronauts on the Moon." },

  // ============ HISTORY'S BIG MOMENTS ============
  { name: "Ancient Egypt", category: "history", emoji: "🏺",
    simpleFact: "Ancient Egypt was a powerful civilization along the Nile River thousands of years ago.",
    facts: ["Ancient Egyptian civilization lasted for about 3,000 years.", "Egyptians were skilled builders, mathematicians, and writers.", "They used a writing system of pictures called hieroglyphics."],
    funFact: "Ancient Egyptians invented one of the earliest forms of paper, called papyrus." },
  { name: "The Great Pyramids", category: "history", emoji: "🔺",
    simpleFact: "The Great Pyramids of Egypt are massive stone tombs built for ancient pharaohs.",
    facts: ["The Great Pyramid of Giza was built over 4,500 years ago.", "It was built without modern machines, using thousands of workers.", "The Great Pyramid was the tallest human-made structure for thousands of years."],
    funFact: "The Great Pyramid was built so precisely that its sides are almost perfectly aligned with true north." },
  { name: "Ancient Rome", category: "history", emoji: "🏛️",
    simpleFact: "Ancient Rome was one of the largest and most powerful empires in history.",
    facts: ["The Roman Empire once stretched across Europe, North Africa, and the Middle East.", "Romans built roads, aqueducts, and buildings that still stand today.", "Roman law and government influenced many modern countries."],
    funFact: "Ancient Rome built roads so well-engineered that some are still usable today, over 2,000 years later." },
  { name: "Ancient Greece", category: "history", emoji: "🏺",
    simpleFact: "Ancient Greece was a civilization known for its ideas about democracy, philosophy, and art.",
    facts: ["Ancient Greeks created one of the first forms of democracy.", "Greek philosophers like Socrates and Aristotle are still studied today.", "The Ancient Greeks also started the tradition of the Olympic Games."],
    funFact: "The word 'democracy' comes from Greek words meaning 'rule by the people.'" },
  { name: "The Vikings", category: "history", emoji: "🛡️",
    simpleFact: "The Vikings were seafaring people from Scandinavia known for their longships and exploration.",
    facts: ["Vikings traveled and traded across much of Europe and beyond.", "They built fast wooden ships called longships.", "Vikings reached North America hundreds of years before Columbus's voyages."],
    funFact: "Viking longships were so well-built that some replicas have successfully crossed the Atlantic Ocean." },
  { name: "The Maya Civilization", category: "history", emoji: "🗿",
    simpleFact: "The Maya were a Central American civilization known for their pyramids, art, and calendar.",
    facts: ["The Maya built large stone cities with temples and pyramids.", "They developed an advanced writing system and calendar.", "Maya astronomers studied the stars and planets in great detail."],
    funFact: "The Maya calendar was so accurate that it closely matches the length of a year as measured today." },
  { name: "The Wright Brothers", category: "history", emoji: "✈️",
    simpleFact: "The Wright brothers achieved the first successful powered airplane flight in 1903.",
    facts: ["Orville and Wilbur Wright were bicycle makers before building airplanes.", "Their first flight took place in Kitty Hawk, North Carolina.", "They tested many glider designs before adding an engine."],
    funFact: "The Wright brothers' first flight was shorter than the length of a football field." },
  { name: "The Moon Landing", category: "history", emoji: "🌕",
    simpleFact: "In 1969, astronauts landed on the Moon for the first time in history.",
    facts: ["Neil Armstrong was the first person to step onto the Moon.", "The mission was called Apollo 11.", "Astronauts collected Moon rocks to bring back and study on Earth."],
    funFact: "The computer that helped land astronauts on the Moon was far less powerful than a modern calculator." },
  { name: "Knights and Castles", category: "history", emoji: "🏰",
    simpleFact: "During medieval times in Europe, knights defended castles and served kings and queens.",
    facts: ["Knights trained for years to fight on horseback in heavy armor.", "Castles were built with thick walls to protect against attacks.", "Many castles had moats, towers, and drawbridges for defense."],
    funFact: "A full suit of knight's armor could weigh as much as 50 pounds." },
  { name: "The Silk Road", category: "history", emoji: "🐪",
    simpleFact: "The Silk Road was an ancient network of trade routes connecting Asia and Europe.",
    facts: ["Traders carried silk, spices, and other goods across thousands of miles.", "The Silk Road also helped spread ideas, art, and inventions between cultures.", "It got its name from the valuable silk fabric traded along the route."],
    funFact: "Goods on the Silk Road sometimes traveled thousands of miles, passing through many traders before reaching their final destination." },
  { name: "Cave Paintings", category: "history", emoji: "🎨",
    simpleFact: "Early humans painted pictures on cave walls thousands of years ago.",
    facts: ["Some cave paintings are more than 30,000 years old.", "Early humans used natural materials like charcoal and clay for paint.", "Cave paintings often show animals like bison, horses, and deer."],
    funFact: "Some ancient cave paintings were made using a technique similar to spray painting, by blowing pigment through hollow bones." },
  { name: "The First Olympic Games", category: "history", emoji: "🏅",
    simpleFact: "The first Olympic Games were held in ancient Greece over 2,700 years ago.",
    facts: ["The first Olympics were held in Olympia, Greece, around 776 BCE.", "Ancient athletes competed in events like running and wrestling.", "The modern Olympic Games, revived in 1896, are inspired by these ancient games."],
    funFact: "In the ancient Olympics, wars between Greek city-states were sometimes paused so athletes could compete safely." },
  { name: "Ancient China", category: "history", emoji: "🏯",
    simpleFact: "Ancient China was home to one of the world's oldest continuous civilizations.",
    facts: ["Ancient China developed early forms of paper, the compass, and gunpowder.", "Powerful dynasties ruled China for thousands of years.", "The Great Wall of China was built to protect against invasions."],
    funFact: "Ancient China invented paper over a thousand years before it became common in Europe." },
  { name: "The Terracotta Army", category: "history", emoji: "🗿",
    simpleFact: "The Terracotta Army is a collection of thousands of life-sized clay soldiers built in ancient China.",
    facts: ["It was built to protect China's first emperor in the afterlife.", "Each of the thousands of statues has a unique face.", "The army was buried underground and stayed hidden for over 2,000 years."],
    funFact: "Farmers accidentally discovered the Terracotta Army in 1974 while digging a well." },
  { name: "The Great Wall", category: "history", emoji: "🧱",
    simpleFact: "The Great Wall of China is one of the largest structures ever built by humans.",
    facts: ["It was built over many centuries by different Chinese dynasties.", "The wall was built to protect against invasions from the north.", "The Great Wall stretches for thousands of miles across mountains and deserts."],
    funFact: "Building the Great Wall took so many workers over so many centuries that no one knows exactly how many people helped build it." },
];

export const DISCOVERY_ENTRIES: DiscoveryEntry[] = RAW.map((entry) => {
  const slug = slugify(entry.name);
  return { ...entry, id: slug, slug };
});

export const DISCOVERY_BY_SLUG: Record<string, DiscoveryEntry> = Object.fromEntries(
  DISCOVERY_ENTRIES.map((e) => [e.slug, e])
);
