import type { GrammarPoint } from "@/types/grammar";

function slugify(title: string): string {
  return title.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/**
 * 66 grammar points spanning CEFR A1 through C2. All explanations, example
 * sentences, and notes on common mistakes are written originally for this
 * product. Coverage and CEFR-level placement follow standard, widely-taught
 * ESL curriculum structure (the same categories any general English course
 * or the CEFR's own published framework would cover) — not copied from any
 * single textbook or proprietary grammar reference.
 */
const RAW: Omit<GrammarPoint, "id" | "slug">[] = [
  // --- Tenses ---
  { title: "Present Simple", category: "tenses", cefrLevel: "A1",
    explanation: "Used for habits, routines, facts, and things that are generally true.",
    structure: "Subject + base verb (add -s/-es for he/she/it)",
    examples: ["She works at a hospital.", "Water boils at 100°C.", "I don't like coffee."],
    commonMistakes: ["Forgetting the -s for he/she/it: 'She work' should be 'She works'."],
    signalWords: ["always", "usually", "often", "every day", "never"],
    compareWith: ["present-continuous"] },
  { title: "Present Continuous", category: "tenses", cefrLevel: "A1",
    explanation: "Used for actions happening right now, or temporary situations around the present.",
    structure: "Subject + am/is/are + verb-ing",
    examples: ["I'm studying for my exam.", "They're staying with friends this week.", "Look — it's raining!"],
    commonMistakes: ["Using it for permanent facts: 'I am liking pizza' should be 'I like pizza' (state verbs usually avoid -ing)."],
    signalWords: ["now", "right now", "at the moment", "currently"],
    compareWith: ["present-simple"] },
  { title: "Past Simple", category: "tenses", cefrLevel: "A1",
    explanation: "Used for completed actions at a specific time in the past.",
    structure: "Subject + past form of the verb (regular: base + -ed)",
    examples: ["We visited Rome last summer.", "She didn't call me yesterday.", "Did you finish the report?"],
    commonMistakes: ["Using the base verb with 'did': 'Did you went?' should be 'Did you go?'."],
    signalWords: ["yesterday", "last week", "in 2020", "ago"],
    compareWith: ["past-continuous", "present-perfect"] },
  { title: "Past Continuous", category: "tenses", cefrLevel: "A2",
    explanation: "Used for an action in progress at a specific moment in the past, often interrupted by another action.",
    structure: "Subject + was/were + verb-ing",
    examples: ["I was cooking when the phone rang.", "They were watching TV all evening.", "What were you doing at 8pm?"],
    commonMistakes: [],
    signalWords: ["while", "when", "at that moment"],
    compareWith: ["past-simple"] },
  { title: "Present Perfect", category: "tenses", cefrLevel: "B1",
    explanation: "Connects the past to the present — for experiences, changes, or actions with a result now, without saying exactly when.",
    structure: "Subject + have/has + past participle",
    examples: ["I've seen that movie already.", "She has just finished her homework.", "We haven't decided yet."],
    commonMistakes: ["Using it with a specific past time: 'I have seen him yesterday' should be 'I saw him yesterday'."],
    signalWords: ["already", "just", "yet", "ever", "never", "since", "for"],
    compareWith: ["past-simple", "present-perfect-continuous"] },
  { title: "Present Perfect Continuous", category: "tenses", cefrLevel: "B2",
    explanation: "Emphasizes the duration of an action that started in the past and continues (or just stopped) — focus on the ongoing activity.",
    structure: "Subject + have/has + been + verb-ing",
    examples: ["I've been studying for three hours.", "She's been working here since 2019.", "Have you been waiting long?"],
    commonMistakes: [],
    signalWords: ["for", "since", "all day", "how long"],
    compareWith: ["present-perfect"] },
  { title: "Past Perfect", category: "tenses", cefrLevel: "B1",
    explanation: "Used for an action completed before another point or action in the past.",
    structure: "Subject + had + past participle",
    examples: ["By the time we arrived, the movie had started.", "She had already left when I called.", "I hadn't seen snow before that trip."],
    commonMistakes: ["Overusing it for simple past sequences: only needed when clarifying which past event came first."],
    signalWords: ["by the time", "before", "after", "already (in the past)"],
    compareWith: ["past-simple", "past-perfect-continuous"] },
  { title: "Past Perfect Continuous", category: "tenses", cefrLevel: "C1",
    explanation: "Emphasizes the duration of an action that was in progress before another past action or moment.",
    structure: "Subject + had + been + verb-ing",
    examples: ["I had been waiting for an hour when she arrived.", "He was tired because he'd been working all night.", "They had been dating for years before they married."],
    commonMistakes: [],
    signalWords: ["for", "since", "before"],
    compareWith: ["past-perfect"] },
  { title: "Future Simple (will)", category: "tenses", cefrLevel: "A1",
    explanation: "Used for predictions, spontaneous decisions, promises, and offers.",
    structure: "Subject + will + base verb",
    examples: ["I think it will rain tomorrow.", "I'll help you with that.", "She won't be happy about this."],
    commonMistakes: ["Using 'will' for prior plans: 'I will go to Paris next month' (already booked) is more naturally 'going to' or present continuous."],
    signalWords: ["tomorrow", "next week", "I think", "probably"],
    compareWith: ["future-with-going-to"] },
  { title: "Future with 'going to'", category: "tenses", cefrLevel: "A1",
    explanation: "Used for plans and intentions decided before the moment of speaking, and for predictions based on present evidence.",
    structure: "Subject + am/is/are + going to + base verb",
    examples: ["We're going to move next year.", "Look at those clouds — it's going to rain.", "I'm not going to argue about this."],
    commonMistakes: [],
    signalWords: ["going to"],
    compareWith: ["future-simple-will"] },
  { title: "Future Continuous", category: "tenses", cefrLevel: "B2",
    explanation: "Used for an action that will be in progress at a specific time in the future.",
    structure: "Subject + will be + verb-ing",
    examples: ["This time tomorrow, I'll be flying to Tokyo.", "She'll be working when you call.", "What will you be doing next weekend?"],
    commonMistakes: [],
    signalWords: ["this time tomorrow", "at 9pm tomorrow"],
    compareWith: ["future-simple-will"] },
  { title: "Future Perfect", category: "tenses", cefrLevel: "C1",
    explanation: "Used for an action that will be completed before a specific point in the future.",
    structure: "Subject + will have + past participle",
    examples: ["By 2030, she will have finished her degree.", "We'll have arrived before the meeting starts.", "Will you have eaten by 7pm?"],
    commonMistakes: [],
    signalWords: ["by the time", "by 2030", "before"],
    compareWith: ["future-simple-will"] },

  // --- Articles ---
  { title: "Indefinite Articles: a / an", category: "articles", cefrLevel: "A1",
    explanation: "Used before a singular countable noun when it's not specific — the first time you mention it, or one of many.",
    structure: "a + consonant sound; an + vowel sound",
    examples: ["I saw a dog in the park.", "She's an engineer.", "It took an hour to finish."],
    commonMistakes: ["Choosing by spelling instead of sound: 'a hour' should be 'an hour' (silent h)."],
    compareWith: ["definite-article-the"] },
  { title: "Definite Article: the", category: "articles", cefrLevel: "A1",
    explanation: "Used when both speaker and listener know which specific thing is being talked about.",
    structure: "the + noun (singular or plural)",
    examples: ["Close the door, please.", "The sun rises in the east.", "I met the woman you told me about."],
    commonMistakes: ["Adding 'the' before general plural or uncountable nouns: 'The music is my passion' (in general) should just be 'Music is my passion'."],
    compareWith: ["indefinite-articles-a-an", "zero-article"] },
  { title: "Zero Article", category: "articles", cefrLevel: "B1",
    explanation: "No article is used before plural or uncountable nouns speaking generally, most proper nouns, and many fixed expressions.",
    examples: ["Dogs are loyal animals.", "I love music.", "She's studying medicine in France."],
    commonMistakes: ["Adding 'the' unnecessarily before general statements or most countries/cities."],
    compareWith: ["definite-article-the"] },

  // --- Nouns ---
  { title: "Countable and Uncountable Nouns", category: "nouns", cefrLevel: "A2",
    explanation: "Countable nouns can be counted and have plural forms (one book, two books). Uncountable nouns can't be counted individually and have no plural (water, advice, information).",
    examples: ["I have three suitcases.", "She gave me some advice.", "There isn't much water left."],
    commonMistakes: ["Pluralizing uncountable nouns: 'informations' should be 'information'."],
    compareWith: ["some-and-any", "much-many-a-lot-of"] },
  { title: "Plural Nouns", category: "nouns", cefrLevel: "A1",
    explanation: "Most nouns add -s to form the plural; some follow irregular patterns.",
    structure: "regular: noun + -s/-es; irregular: memorized forms (child → children)",
    examples: ["two cats", "three boxes", "several children"],
    commonMistakes: ["Regularizing irregular plurals: 'childs' should be 'children'; 'mans' should be 'men'."] },
  { title: "Possessive 's (Apostrophe S)", category: "nouns", cefrLevel: "A1",
    explanation: "Shows that something belongs to someone. Add 's to singular nouns, just an apostrophe to regular plural nouns.",
    structure: "singular: noun + 's; plural ending in -s: noun + '",
    examples: ["This is Maria's car.", "The students' books are on the desk.", "It's the children's playground."],
    commonMistakes: ["Confusing 'its' (possessive) with 'it's' (it is)."] },
  { title: "Compound Nouns", category: "nouns", cefrLevel: "B1",
    explanation: "Two or more words combined to make a new noun with its own meaning, written as one word, two words, or hyphenated.",
    examples: ["a toothbrush", "a bus stop", "a mother-in-law"],
    commonMistakes: ["Guessing the spacing/hyphenation — it varies by word and often needs to be learned individually."] },

  // --- Pronouns ---
  { title: "Personal Pronouns", category: "pronouns", cefrLevel: "A1",
    explanation: "Replace nouns already mentioned. Subject pronouns (I, you, he...) do the action; object pronouns (me, you, him...) receive it.",
    examples: ["She loves him.", "We saw them at the party.", "It was nice of you to help us."],
    commonMistakes: ["Mixing subject and object forms: 'Me and him went' should be 'He and I went'."] },
  { title: "Possessive Pronouns and Adjectives", category: "pronouns", cefrLevel: "A1",
    explanation: "Possessive adjectives (my, your, his...) come before a noun. Possessive pronouns (mine, yours, his...) replace the noun entirely.",
    examples: ["This is my book.", "That book is mine.", "Is this bag yours or hers?"],
    commonMistakes: ["Using an apostrophe with possessive pronouns: 'This is her's' should be 'This is hers' (no apostrophe)."] },
  { title: "Reflexive Pronouns", category: "pronouns", cefrLevel: "A2",
    explanation: "Used when the subject and object of a verb are the same person or thing (myself, yourself, himself, herself, itself, ourselves, yourselves, themselves).",
    examples: ["I taught myself to play guitar.", "Be careful, you might hurt yourself.", "They enjoyed themselves at the party."],
    commonMistakes: ["Using a reflexive pronoun when it's not needed: 'I washed myself the car' should be 'I washed the car myself' (for emphasis) or just 'I washed the car'."] },
  { title: "Relative Pronouns", category: "pronouns", cefrLevel: "B1",
    explanation: "Introduce a clause that gives more information about a noun: who/whom (people), which (things), that (people or things), whose (possession).",
    examples: ["The man who called is my uncle.", "This is the book that I told you about.", "She's the artist whose paintings sell for millions."],
    commonMistakes: ["Using 'which' for people instead of 'who': 'The man which called' should be 'The man who called'."],
    compareWith: ["defining-relative-clauses"] },
  { title: "Indefinite Pronouns", category: "pronouns", cefrLevel: "B1",
    explanation: "Refer to unspecified people or things: someone/anyone/no one/everyone, something/anything/nothing/everything.",
    examples: ["Someone left their umbrella here.", "I didn't say anything.", "Everyone enjoyed the concert."],
    commonMistakes: ["Double negatives: 'I didn't see nobody' should be 'I didn't see anybody.'"] },

  // --- Adjectives & adverbs ---
  { title: "Comparative Adjectives", category: "adjectives-adverbs", cefrLevel: "A2",
    explanation: "Used to compare two things. Short adjectives add -er; longer adjectives use 'more'.",
    structure: "short: adjective + -er + than; long: more + adjective + than",
    examples: ["This bag is bigger than that one.", "She's more experienced than her colleague.", "Today is hotter than yesterday."],
    commonMistakes: ["Doubling the comparative: 'more bigger' should be just 'bigger'."],
    compareWith: ["superlative-adjectives"] },
  { title: "Superlative Adjectives", category: "adjectives-adverbs", cefrLevel: "A2",
    explanation: "Used to compare three or more things and identify the extreme. Short adjectives add -est; longer ones use 'most'.",
    structure: "short: the + adjective + -est; long: the most + adjective",
    examples: ["This is the tallest building in the city.", "It was the most interesting talk of the day.", "He's the best player on the team."],
    commonMistakes: ["Forgetting 'the': 'This is tallest building' should be 'the tallest building'."],
    compareWith: ["comparative-adjectives"] },
  { title: "Order of Adjectives", category: "adjectives-adverbs", cefrLevel: "B2",
    explanation: "When using multiple adjectives before a noun, they typically follow an order: opinion, size, age, shape, color, origin, material, purpose.",
    examples: ["a beautiful old red car", "a small round wooden table", "an expensive Italian leather bag"],
    commonMistakes: ["Random ordering that sounds unnatural to native speakers, even if grammatically 'allowed'."] },
  { title: "Adverbs of Frequency", category: "adjectives-adverbs", cefrLevel: "A1",
    explanation: "Describe how often something happens: always, usually, often, sometimes, rarely, never. They usually go before the main verb but after 'to be'.",
    examples: ["I always drink coffee in the morning.", "She is rarely late.", "We sometimes eat out on Fridays."],
    commonMistakes: ["Wrong position: 'I drink always coffee' should be 'I always drink coffee'."] },
  { title: "Adverbs of Manner", category: "adjectives-adverbs", cefrLevel: "A2",
    explanation: "Describe how an action is done, usually formed by adding -ly to an adjective, and typically placed after the verb.",
    examples: ["She sings beautifully.", "He drives carefully.", "They worked quickly to finish on time."],
    commonMistakes: ["Using the adjective instead of the adverb: 'She sings beautiful' should be 'She sings beautifully'."] },
  { title: "Gradable and Non-Gradable Adjectives", category: "adjectives-adverbs", cefrLevel: "C1",
    explanation: "Gradable adjectives (big, cold) can be modified by 'very' and have degrees. Non-gradable adjectives (freezing, enormous) already describe an extreme and pair with 'absolutely' instead.",
    examples: ["It's very cold today. (gradable)", "It's absolutely freezing! (non-gradable)", "The house is enormous, not 'very enormous'."],
    commonMistakes: ["Saying 'very freezing' or 'very enormous' — non-gradable adjectives don't take 'very'."] },

  // --- Modals ---
  { title: "Can / Could (ability)", category: "modals", cefrLevel: "A1",
    explanation: "'Can' expresses present ability or permission; 'could' expresses past ability or a more polite request.",
    examples: ["I can swim.", "She could read by age four.", "Could you help me, please?"],
    commonMistakes: ["Adding 'to': 'I can to swim' should be 'I can swim' (modals are followed by the base verb, no 'to')."] },
  { title: "Must / Have to (obligation)", category: "modals", cefrLevel: "A2",
    explanation: "Both express obligation. 'Must' often reflects the speaker's own feeling of necessity; 'have to' often reflects an external rule.",
    examples: ["I must call my mother tonight.", "You have to wear a seatbelt by law.", "We don't have to leave yet."],
    commonMistakes: ["Confusing negatives: 'must not' means it's forbidden, while 'don't have to' means it's not necessary — very different meanings."] },
  { title: "Should / Ought to (advice)", category: "modals", cefrLevel: "A2",
    explanation: "Used to give advice or say what's the right thing to do. 'Ought to' is more formal and less common in speech.",
    examples: ["You should see a doctor.", "We ought to leave soon.", "You shouldn't stay up so late."],
    commonMistakes: [] },
  { title: "May / Might (possibility)", category: "modals", cefrLevel: "B1",
    explanation: "Used to express that something is possible but not certain. 'Might' generally suggests slightly less certainty than 'may'.",
    examples: ["It may rain later.", "She might come to the party.", "We may not have enough time."],
    commonMistakes: ["Confusing with permission use of 'may' ('May I leave?') — context makes the meaning clear."] },
  { title: "Modal Verbs of Deduction", category: "modals", cefrLevel: "B2",
    explanation: "Used to guess how likely something is, based on evidence: must (very sure), could/might/may (possible), can't (very sure it's not true).",
    examples: ["He must be tired after that flight.", "She could be at work still.", "That can't be right."],
    commonMistakes: ["Using 'mustn't' for negative deduction — the correct form is 'can't': 'That mustn't be true' should be 'That can't be true'."] },
  { title: "Modals in the Past", category: "modals", cefrLevel: "B2",
    explanation: "Modal + have + past participle expresses past possibility, deduction, or regret.",
    structure: "modal + have + past participle",
    examples: ["You should have called me.", "She might have missed the train.", "He must have forgotten."],
    commonMistakes: ["Writing 'should of' instead of 'should have' — a very common spelling mistake from how it sounds when spoken."] },

  // --- Conditionals ---
  { title: "Zero Conditional", category: "conditionals", cefrLevel: "A2",
    explanation: "Used for general truths and facts that are always the result of a condition.",
    structure: "If + present simple, present simple",
    examples: ["If you heat ice, it melts.", "If it rains, the ground gets wet.", "Plants die if they don't get water."],
    commonMistakes: [],
    compareWith: ["first-conditional"] },
  { title: "First Conditional", category: "conditionals", cefrLevel: "A2",
    explanation: "Used for real, likely situations in the future and their probable results.",
    structure: "If + present simple, will + base verb",
    examples: ["If it rains, we'll stay home.", "If you study hard, you'll pass the exam.", "I'll call you if I finish early."],
    commonMistakes: ["Using 'will' in the if-clause: 'If it will rain' should be 'If it rains'."],
    compareWith: ["zero-conditional", "second-conditional"] },
  { title: "Second Conditional", category: "conditionals", cefrLevel: "B1",
    explanation: "Used for unreal or unlikely present/future situations and their imagined results.",
    structure: "If + past simple, would + base verb",
    examples: ["If I won the lottery, I would travel the world.", "If I were you, I'd apologize.", "She would help if she had time."],
    commonMistakes: [],
    compareWith: ["first-conditional", "third-conditional"] },
  { title: "Third Conditional", category: "conditionals", cefrLevel: "B2",
    explanation: "Used for unreal situations in the past and how they would have turned out differently.",
    structure: "If + past perfect, would have + past participle",
    examples: ["If I had studied, I would have passed.", "If she hadn't left early, she wouldn't have missed the bus.", "We would have come if you had invited us."],
    commonMistakes: [],
    compareWith: ["second-conditional", "mixed-conditionals"] },
  { title: "Mixed Conditionals", category: "conditionals", cefrLevel: "C1",
    explanation: "Combines different time frames — typically a past condition with a present result, or a present condition with a past result.",
    structure: "If + past perfect, would + base verb (past condition, present result)",
    examples: ["If I had studied medicine, I would be a doctor now.", "If she weren't so busy, she would have come to the party.", "If he had saved money, he would be financially secure today."],
    commonMistakes: [],
    compareWith: ["third-conditional"] },

  // --- Passive voice ---
  { title: "Passive Voice: Present", category: "passive-voice", cefrLevel: "B1",
    explanation: "Used when the action matters more than who does it, in present tenses.",
    structure: "Subject + am/is/are (+ being) + past participle",
    examples: ["The report is written every month.", "The house is being painted.", "English is spoken here."],
    commonMistakes: [],
    compareWith: ["passive-voice-past"] },
  { title: "Passive Voice: Past", category: "passive-voice", cefrLevel: "B1",
    explanation: "Same idea as present passive, but describing a completed or ongoing past action.",
    structure: "Subject + was/were (+ being) + past participle",
    examples: ["The bridge was built in 1930.", "The cake was eaten before I arrived.", "The car was being repaired all week."],
    commonMistakes: [],
    compareWith: ["passive-voice-present"] },
  { title: "Passive Voice: Other Tenses & Modals", category: "passive-voice", cefrLevel: "B2",
    explanation: "The passive can combine with perfect tenses, future forms, and modal verbs.",
    structure: "modal/auxiliary + be + past participle",
    examples: ["The results will be announced tomorrow.", "The problem has been fixed.", "This must be done carefully."],
    commonMistakes: [] },

  // --- Reported speech ---
  { title: "Reported Statements", category: "reported-speech", cefrLevel: "B1",
    explanation: "When reporting what someone said, tenses usually shift one step back into the past ('backshift'), and pronouns/time words adjust.",
    examples: ["\"I'm tired,\" she said. → She said (that) she was tired.", "\"I'll call you,\" he said. → He said he would call me.", "\"We live here,\" they said. → They said they lived there."],
    commonMistakes: ["Forgetting to shift the tense back, or forgetting to adjust pronouns and time/place words."] },
  { title: "Reported Questions", category: "reported-speech", cefrLevel: "B2",
    explanation: "Reported questions use normal statement word order (no inversion) and drop the question mark. Yes/no questions add 'if' or 'whether'.",
    examples: ["\"Where do you live?\" → She asked where I lived.", "\"Are you coming?\" → He asked if I was coming.", "\"What time is it?\" → I asked what time it was."],
    commonMistakes: ["Keeping question word order: 'She asked where did I live' should be 'She asked where I lived'."] },
  { title: "Reported Commands and Requests", category: "reported-speech", cefrLevel: "B2",
    explanation: "Reported with 'to' + base verb (positive) or 'not to' + base verb (negative), usually after 'tell' or 'ask'.",
    examples: ["\"Sit down,\" she said. → She told him to sit down.", "\"Don't be late,\" he said. → He told her not to be late.", "\"Please help me,\" she said. → She asked him to help her."],
    commonMistakes: [] },

  // --- Questions ---
  { title: "Yes/No Questions", category: "questions", cefrLevel: "A1",
    explanation: "Formed by inverting the subject and auxiliary verb (or adding 'do/does/did' if there's no other auxiliary).",
    structure: "Auxiliary + subject + base verb...?",
    examples: ["Do you like coffee?", "Is she coming?", "Did they win?"],
    commonMistakes: ["Forgetting 'do/does' support: 'Like you coffee?' should be 'Do you like coffee?'."] },
  { title: "Wh- Questions", category: "questions", cefrLevel: "A1",
    explanation: "Start with a question word (what, where, when, why, who, how) followed by the same auxiliary + subject structure as yes/no questions.",
    structure: "Question word + auxiliary + subject + base verb...?",
    examples: ["What do you want?", "Where is the station?", "Why didn't you call?"],
    commonMistakes: [] },
  { title: "Question Tags", category: "questions", cefrLevel: "B1",
    explanation: "A short question added to the end of a statement to confirm information or invite agreement — positive statement gets a negative tag, and vice versa.",
    examples: ["You're coming, aren't you?", "She doesn't like it, does she?", "It's cold today, isn't it?"],
    commonMistakes: ["Matching the tag's polarity to the statement instead of reversing it."] },
  { title: "Indirect Questions", category: "questions", cefrLevel: "B2",
    explanation: "A more polite way to ask questions, embedded in a longer phrase, using statement word order (no inversion).",
    examples: ["Could you tell me where the station is?", "Do you know what time it is?", "I was wondering if you could help."],
    commonMistakes: ["Keeping question inversion inside the embedded clause: 'Do you know where is the station?' should be 'Do you know where the station is?'."] },

  // --- Gerunds & infinitives ---
  { title: "Verb + -ing (Gerunds)", category: "gerunds-infinitives", cefrLevel: "B1",
    explanation: "Some verbs are followed by the -ing form of the next verb, not the infinitive: enjoy, avoid, finish, suggest, mind, among others.",
    examples: ["I enjoy reading.", "She avoided answering the question.", "Would you mind closing the window?"],
    commonMistakes: ["Using 'to' + infinitive after these verbs: 'I enjoy to read' should be 'I enjoy reading'."],
    compareWith: ["verb-infinitive"] },
  { title: "Verb + Infinitive", category: "gerunds-infinitives", cefrLevel: "B1",
    explanation: "Some verbs are followed by 'to' + base verb, not the -ing form: want, decide, hope, plan, promise, among others.",
    examples: ["I want to travel more.", "She decided to quit her job.", "We hope to see you soon."],
    commonMistakes: ["Using -ing after these verbs: 'I want traveling' should be 'I want to travel'."],
    compareWith: ["verb-ing-gerunds"] },
  { title: "Gerund vs Infinitive (Meaning Changes)", category: "gerunds-infinitives", cefrLevel: "C1",
    explanation: "A handful of verbs (remember, stop, try, forget) change meaning depending on whether they're followed by -ing or the infinitive.",
    examples: ["I stopped smoking. (I quit the habit) vs. I stopped to smoke. (I paused to smoke)", "Remember to lock the door. (don't forget) vs. I remember locking the door. (a memory of doing it)", "Try calling her. (as an experiment) vs. Try to call her. (make an effort)"],
    commonMistakes: ["Treating these as interchangeable — the meaning genuinely changes with the form."] },

  // --- Relative clauses ---
  { title: "Defining Relative Clauses", category: "relative-clauses", cefrLevel: "B1",
    explanation: "Give essential information that identifies which person or thing is being talked about — no commas, and 'that' is often possible.",
    examples: ["The woman who lives next door is a doctor.", "This is the book that I mentioned.", "I need a phone that has a good camera."],
    commonMistakes: ["Adding unnecessary commas, which changes it into a non-defining clause."],
    compareWith: ["non-defining-relative-clauses"] },
  { title: "Non-Defining Relative Clauses", category: "relative-clauses", cefrLevel: "B2",
    explanation: "Add extra, non-essential information, set off by commas. 'That' cannot be used here.",
    examples: ["My brother, who lives in Canada, is visiting next month.", "The Eiffel Tower, which was built in 1889, attracts millions of visitors.", "Paris, where I studied, is a beautiful city."],
    commonMistakes: ["Using 'that' instead of 'who/which': non-defining clauses require who/which, never 'that'."],
    compareWith: ["defining-relative-clauses"] },

  // --- Conjunctions ---
  { title: "Coordinating Conjunctions (FANBOYS)", category: "conjunctions", cefrLevel: "A2",
    explanation: "For, And, Nor, But, Or, Yet, So — connect two independent clauses or items of equal grammatical importance.",
    examples: ["I wanted to go, but I was too tired.", "She studies hard, so she gets good grades.", "We can walk or take the bus."],
    commonMistakes: ["Missing the comma before the conjunction when joining two full sentences."] },
  { title: "Subordinating Conjunctions", category: "conjunctions", cefrLevel: "B1",
    explanation: "Introduce a dependent clause and show a relationship (time, reason, contrast, condition) with the main clause: because, although, since, if, when, while.",
    examples: ["I stayed home because I was sick.", "Although it was raining, we went for a walk.", "She called while I was cooking."],
    commonMistakes: [] },
  { title: "Linking Words for Contrast", category: "conjunctions", cefrLevel: "B2",
    explanation: "'However' and 'nevertheless' link two separate sentences (often after a semicolon or as a new sentence); 'although' and 'though' join clauses within one sentence.",
    examples: ["It was expensive. However, we bought it anyway.", "Although it was expensive, we bought it.", "The plan was risky; nevertheless, they went ahead."],
    commonMistakes: ["Using 'however' like 'although': 'However it was expensive, we bought it' should use 'although' instead."] },

  // --- Determiners & quantifiers ---
  { title: "Some and Any", category: "determiners-quantifiers", cefrLevel: "A1",
    explanation: "'Some' is generally used in positive sentences and offers; 'any' is used in negatives and questions.",
    examples: ["I have some questions.", "Do you have any milk?", "There isn't any bread left."],
    commonMistakes: ["Using 'any' in an offer: 'Do you want any coffee?' is grammatically fine but 'some' sounds more natural for offers."] },
  { title: "Much, Many, A Lot Of", category: "determiners-quantifiers", cefrLevel: "A2",
    explanation: "'Much' is used with uncountable nouns, 'many' with countable plural nouns, and 'a lot of' works with both, especially in positive sentences.",
    examples: ["I don't have much time.", "There are many options.", "She has a lot of friends."],
    commonMistakes: ["Using 'much' with countable nouns: 'much books' should be 'many books'."] },
  { title: "Few and Little", category: "determiners-quantifiers", cefrLevel: "B1",
    explanation: "'Few' (countable) and 'little' (uncountable) suggest 'not enough'; 'a few' and 'a little' suggest 'a small amount, but enough'.",
    examples: ["I have few friends here. (implies loneliness)", "I have a few friends here. (implies some, positively)", "There's little hope left. vs. There's a little hope left."],
    commonMistakes: ["Missing the 'a' changes the whole meaning from positive to negative — a subtle but important distinction."] },
  { title: "Every, Each, All", category: "determiners-quantifiers", cefrLevel: "B1",
    explanation: "'Every' and 'each' both refer to individual members of a group (each is more individual-focused), while 'all' refers to the group as a whole.",
    examples: ["Every student passed the test.", "Each student received individual feedback.", "All students must register by Friday."],
    commonMistakes: ["Using 'all' with a singular verb: 'All student is here' should be 'All students are here'."] },

  // --- Sentence structure ---
  { title: "Word Order in Statements", category: "sentence-structure", cefrLevel: "A1",
    explanation: "Standard English statement order is Subject + Verb + Object, with time expressions usually at the end.",
    structure: "Subject + Verb + Object (+ Time/Place)",
    examples: ["I eat breakfast every morning.", "She reads books at night.", "We watched a movie yesterday."],
    commonMistakes: ["Placing the object before the verb (common if translating directly from another language's word order)."] },
  { title: "Inversion for Emphasis", category: "sentence-structure", cefrLevel: "C2",
    explanation: "Certain negative or restrictive adverbials moved to the front of a sentence for emphasis trigger subject-auxiliary inversion, a hallmark of formal/literary style.",
    examples: ["Never have I seen such a mess.", "Rarely does she complain.", "Not only did he apologize, but he also fixed the problem."],
    commonMistakes: ["Forgetting to invert after the fronted adverbial — the whole point of the structure is the inversion."] },
  { title: "Cleft Sentences", category: "sentence-structure", cefrLevel: "C2",
    explanation: "Split a single idea into two clauses to emphasize a particular part of the sentence, often with 'It is/was...' or 'What... is...'.",
    examples: ["It was Sarah who solved the problem.", "What I need is more time.", "It wasn't until later that I understood."],
    commonMistakes: ["Overusing them where a normal sentence would be more natural — cleft sentences work best for genuine emphasis or contrast."] },
];

export const GRAMMAR_POINTS: GrammarPoint[] = RAW.map((entry) => {
  const slug = slugify(entry.title);
  return { ...entry, id: slug, slug };
});

export const GRAMMAR_POINTS_BY_SLUG: Record<string, GrammarPoint> = Object.fromEntries(
  GRAMMAR_POINTS.map((g) => [g.slug, g])
);
